
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        retencion
* GENERATION DATE:  31.07.2015
* CLASS FILE:       C:\wamp\www\genera_clase/generated_classes/class.retencion.php
* FOR MYSQL TABLE:  retenciones
* FOR MYSQL DB:     aurora
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* modify: >> www.aurora-ec.net >> (download for free!)
* -------------------------------------------------------
*
*/
include_once("class.aurora.php");
// **********************
// CLASS DECLARATION
// **********************

class retencion
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************


public $idRetenciones;   // (normal Attribute)
public $ambiente;   // (normal Attribute)
public $tipoEmision;   // (normal Attribute)
public $ruc;   // (normal Attribute)
public $claveAcceso;   // (normal Attribute)
public $estab;   // (normal Attribute)
public $codDoc;   // (normal Attribute)
public $punto;   // (normal Attribute)
public $sq;   // (normal Attribute)
public $fechaEmision;   // (normal Attribute)
public $tipoId;   // (normal Attribute)
public $nroId;   // (normal Attribute)
public $razonSujeto;   // (normal Attribute)
public $totalRetencion;   // (normal Attribute)
public $codDocSustento;   // (normal Attribute)
public $numDocSustento;   // (normal Attribute)
public $fechaEmisionDS;   // (normal Attribute)
public $periodoFiscal;   // (normal Attribute)
public $estado;   // (normal Attribute)
public $fechaAutoriza;   // (normal Attribute)
public $numeroAutoriza;   // (normal Attribute)
public $codMsg;   // (normal Attribute)
public $mensaje;   // (normal Attribute)
public $msgAdicional;   // (normal Attribute)
public $TipoError;   // (normal Attribute)

var $db; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function __construct()
{

$this->db = new AuroraDB();
}

function __destruct()
{


}

function genJson_retencion($jsonString)
{
$_SESSION['idRetenciones'] = $jsonString->idRetenciones;
$_SESSION['ambiente'] = $jsonString->ambiente;
$_SESSION['tipoEmision'] = $jsonString->tipoEmision;
$_SESSION['ruc'] = $jsonString->ruc;
$_SESSION['claveAcceso'] = $jsonString->claveAcceso;
$_SESSION['estab'] = $jsonString->estab;
$_SESSION['codDoc'] = $jsonString->codDoc;
$_SESSION['punto'] = $jsonString->punto;
$_SESSION['sq'] = $jsonString->sq;
$_SESSION['fechaEmision'] = $jsonString->fechaEmision;
$_SESSION['tipoId'] = $jsonString->tipoId;
$_SESSION['nroId'] = $jsonString->nroId;
$_SESSION['razonSujeto'] = $jsonString->razonSujeto;
$_SESSION['totalRetencion'] = $jsonString->totalRetencion;
$_SESSION['codDocSustento'] = $jsonString->codDocSustento;
$_SESSION['numDocSustento'] = $jsonString->numDocSustento;
$_SESSION['fechaEmisionDS'] = $jsonString->fechaEmisionDS;
$_SESSION['periodoFiscal'] = $jsonString->periodoFiscal;
$_SESSION['estado'] = $jsonString->estado;
$_SESSION['fechaAutoriza'] = $jsonString->fechaAutoriza;
$_SESSION['numeroAutoriza'] = $jsonString->numeroAutoriza;
$_SESSION['codMsg'] = $jsonString->codMsg;
$_SESSION['mensaje'] = $jsonString->mensaje;
$_SESSION['msgAdicional'] = $jsonString->msgAdicional;
$_SESSION['TipoError'] = $jsonString->TipoError;

}

function genInsert_retencion($obj_retencion)
{
$obj_retencion->setidRetenciones($_SESSION['idRetenciones']);
$obj_retencion->setambiente($_SESSION['ambiente']);
$obj_retencion->settipoEmision($_SESSION['tipoEmision']);
$obj_retencion->setruc($_SESSION['ruc']);
$obj_retencion->setclaveAcceso($_SESSION['claveAcceso']);
$obj_retencion->setestab($_SESSION['estab']);
$obj_retencion->setcodDoc($_SESSION['codDoc']);
$obj_retencion->setpunto($_SESSION['punto']);
$obj_retencion->setsq($_SESSION['sq']);
$obj_retencion->setfechaEmision($_SESSION['fechaEmision']);
$obj_retencion->settipoId($_SESSION['tipoId']);
$obj_retencion->setnroId($_SESSION['nroId']);
$obj_retencion->setrazonSujeto($_SESSION['razonSujeto']);
$obj_retencion->settotalRetencion($_SESSION['totalRetencion']);
$obj_retencion->setcodDocSustento($_SESSION['codDocSustento']);
$obj_retencion->setnumDocSustento($_SESSION['numDocSustento']);
$obj_retencion->setfechaEmisionDS($_SESSION['fechaEmisionDS']);
$obj_retencion->setperiodoFiscal($_SESSION['periodoFiscal']);
$obj_retencion->setestado($_SESSION['estado']);
$obj_retencion->setfechaAutoriza($_SESSION['fechaAutoriza']);
$obj_retencion->setnumeroAutoriza($_SESSION['numeroAutoriza']);
$obj_retencion->setcodMsg($_SESSION['codMsg']);
$obj_retencion->setmensaje($_SESSION['mensaje']);
$obj_retencion->setmsgAdicional($_SESSION['msgAdicional']);
$obj_retencion->setTipoError($_SESSION['TipoError']);

}

// **********************
// GETTER METHODS
// **********************


function getidRetenciones()
{
return $this->idRetenciones;
}

function getambiente()
{
return $this->ambiente;
}

function gettipoEmision()
{
return $this->tipoEmision;
}

function getruc()
{
return $this->ruc;
}

function getclaveAcceso()
{
return $this->claveAcceso;
}

function getestab()
{
return $this->estab;
}

function getcodDoc()
{
return $this->codDoc;
}

function getpunto()
{
return $this->punto;
}

function getsq()
{
return $this->sq;
}

function getfechaEmision()
{
return $this->fechaEmision;
}

function gettipoId()
{
return $this->tipoId;
}

function getnroId()
{
return $this->nroId;
}

function getrazonSujeto()
{
return $this->razonSujeto;
}

function gettotalRetencion()
{
return $this->totalRetencion;
}

function getcodDocSustento()
{
return $this->codDocSustento;
}

function getnumDocSustento()
{
return $this->numDocSustento;
}

function getfechaEmisionDS()
{
return $this->fechaEmisionDS;
}

function getperiodoFiscal()
{
return $this->periodoFiscal;
}

function getestado()
{
return $this->estado;
}

function getfechaAutoriza()
{
return $this->fechaAutoriza;
}

function getnumeroAutoriza()
{
return $this->numeroAutoriza;
}

function getcodMsg()
{
return $this->codMsg;
}

function getmensaje()
{
return $this->mensaje;
}

function getmsgAdicional()
{
return $this->msgAdicional;
}

function getTipoError()
{
return $this->TipoError;
}

// **********************
// SETTER METHODS
// **********************


function setidRetenciones($val)
{
$this->idRetenciones =  $val;
}

function setambiente($val)
{
$this->ambiente =  $val;
}

function settipoEmision($val)
{
$this->tipoEmision =  $val;
}

function setruc($val)
{
$this->ruc =  $val;
}

function setclaveAcceso($val)
{
$this->claveAcceso =  $val;
}

function setestab($val)
{
$this->estab =  $val;
}

function setcodDoc($val)
{
$this->codDoc =  $val;
}

function setpunto($val)
{
$this->punto =  $val;
}

function setsq($val)
{
$this->sq =  $val;
}

function setfechaEmision($val)
{
$this->fechaEmision =  $val;
}

function settipoId($val)
{
$this->tipoId =  $val;
}

function setnroId($val)
{
$this->nroId =  $val;
}

function setrazonSujeto($val)
{
$this->razonSujeto =  $val;
}

function settotalRetencion($val)
{
$this->totalRetencion =  $val;
}

function setcodDocSustento($val)
{
$this->codDocSustento =  $val;
}

function setnumDocSustento($val)
{
$this->numDocSustento =  $val;
}

function setfechaEmisionDS($val)
{
$this->fechaEmisionDS =  $val;
}

function setperiodoFiscal($val)
{
$this->periodoFiscal =  $val;
}

function setestado($val)
{
$this->estado =  $val;
}

function setfechaAutoriza($val)
{
$this->fechaAutoriza =  $val;
}

function setnumeroAutoriza($val)
{
$this->numeroAutoriza =  $val;
}

function setcodMsg($val)
{
$this->codMsg =  $val;
}

function setmensaje($val)
{
$this->mensaje =  $val;
}

function setmsgAdicional($val)
{
$this->msgAdicional =  $val;
}

function setTipoError($val)
{
$this->TipoError =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM retenciones WHERE idRetenciones = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idRetenciones, $db_ambiente, $db_tipoEmision, $db_ruc, $db_claveAcceso, $db_estab, $db_codDoc, $db_punto, $db_sq, $db_fechaEmision, $db_tipoId, $db_nroId, $db_razonSujeto, $db_totalRetencion, $db_codDocSustento, $db_numDocSustento, $db_fechaEmisionDS, $db_periodoFiscal, $db_estado, $db_fechaAutoriza, $db_numeroAutoriza, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_TipoError);
            $stmt->execute();
                if ($stmt->fetch()) {
                $this->idRetenciones = $db_idRetenciones;
$this->ambiente = $db_ambiente;
$this->tipoEmision = $db_tipoEmision;
$this->ruc = $db_ruc;
$this->claveAcceso = $db_claveAcceso;
$this->estab = $db_estab;
$this->codDoc = $db_codDoc;
$this->punto = $db_punto;
$this->sq = $db_sq;
$this->fechaEmision = $db_fechaEmision;
$this->tipoId = $db_tipoId;
$this->nroId = $db_nroId;
$this->razonSujeto = $db_razonSujeto;
$this->totalRetencion = $db_totalRetencion;
$this->codDocSustento = $db_codDocSustento;
$this->numDocSustento = $db_numDocSustento;
$this->fechaEmisionDS = $db_fechaEmisionDS;
$this->periodoFiscal = $db_periodoFiscal;
$this->estado = $db_estado;
$this->fechaAutoriza = $db_fechaAutoriza;
$this->numeroAutoriza = $db_numeroAutoriza;
$this->codMsg = $db_codMsg;
$this->mensaje = $db_mensaje;
$this->msgAdicional = $db_msgAdicional;
$this->TipoError = $db_TipoError;


            }
$db->close();
}

// *******************************
// SELECT METHOD / FETCH LOOP
// *******************************

function seleccionar($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM retenciones WHERE idRetenciones = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idRetenciones, $db_ambiente, $db_tipoEmision, $db_ruc, $db_claveAcceso, $db_estab, $db_codDoc, $db_punto, $db_sq, $db_fechaEmision, $db_tipoId, $db_nroId, $db_razonSujeto, $db_totalRetencion, $db_codDocSustento, $db_numDocSustento, $db_fechaEmisionDS, $db_periodoFiscal, $db_estado, $db_fechaAutoriza, $db_numeroAutoriza, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_TipoError);
            $stmt->execute();
                while ($stmt->fetch()) {
                $obj_retencion->idRetenciones = $db_idRetenciones;
$obj_retencion->ambiente = $db_ambiente;
$obj_retencion->tipoEmision = $db_tipoEmision;
$obj_retencion->ruc = $db_ruc;
$obj_retencion->claveAcceso = $db_claveAcceso;
$obj_retencion->estab = $db_estab;
$obj_retencion->codDoc = $db_codDoc;
$obj_retencion->punto = $db_punto;
$obj_retencion->sq = $db_sq;
$obj_retencion->fechaEmision = $db_fechaEmision;
$obj_retencion->tipoId = $db_tipoId;
$obj_retencion->nroId = $db_nroId;
$obj_retencion->razonSujeto = $db_razonSujeto;
$obj_retencion->totalRetencion = $db_totalRetencion;
$obj_retencion->codDocSustento = $db_codDocSustento;
$obj_retencion->numDocSustento = $db_numDocSustento;
$obj_retencion->fechaEmisionDS = $db_fechaEmisionDS;
$obj_retencion->periodoFiscal = $db_periodoFiscal;
$obj_retencion->estado = $db_estado;
$obj_retencion->fechaAutoriza = $db_fechaAutoriza;
$obj_retencion->numeroAutoriza = $db_numeroAutoriza;
$obj_retencion->codMsg = $db_codMsg;
$obj_retencion->mensaje = $db_mensaje;
$obj_retencion->msgAdicional = $db_msgAdicional;
$obj_retencion->TipoError = $db_TipoError;


            }
$db->close();
}

// *******************************
// SELECT METHOD / FETCH LOOP
// *******************************

function recorrer($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM retenciones WHERE idRetenciones = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idRetenciones, $db_ambiente, $db_tipoEmision, $db_ruc, $db_claveAcceso, $db_estab, $db_codDoc, $db_punto, $db_sq, $db_fechaEmision, $db_tipoId, $db_nroId, $db_razonSujeto, $db_totalRetencion, $db_codDocSustento, $db_numDocSustento, $db_fechaEmisionDS, $db_periodoFiscal, $db_estado, $db_fechaAutoriza, $db_numeroAutoriza, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_TipoError);
            $stmt->execute();
                if ($stmt->fetch()) {
                $_SESSION['idRetenciones'] = $obj_retencion->getidRetenciones();
$_SESSION['ambiente'] = $obj_retencion->getambiente();
$_SESSION['tipoEmision'] = $obj_retencion->gettipoEmision();
$_SESSION['ruc'] = $obj_retencion->getruc();
$_SESSION['claveAcceso'] = $obj_retencion->getclaveAcceso();
$_SESSION['estab'] = $obj_retencion->getestab();
$_SESSION['codDoc'] = $obj_retencion->getcodDoc();
$_SESSION['punto'] = $obj_retencion->getpunto();
$_SESSION['sq'] = $obj_retencion->getsq();
$_SESSION['fechaEmision'] = $obj_retencion->getfechaEmision();
$_SESSION['tipoId'] = $obj_retencion->gettipoId();
$_SESSION['nroId'] = $obj_retencion->getnroId();
$_SESSION['razonSujeto'] = $obj_retencion->getrazonSujeto();
$_SESSION['totalRetencion'] = $obj_retencion->gettotalRetencion();
$_SESSION['codDocSustento'] = $obj_retencion->getcodDocSustento();
$_SESSION['numDocSustento'] = $obj_retencion->getnumDocSustento();
$_SESSION['fechaEmisionDS'] = $obj_retencion->getfechaEmisionDS();
$_SESSION['periodoFiscal'] = $obj_retencion->getperiodoFiscal();
$_SESSION['estado'] = $obj_retencion->getestado();
$_SESSION['fechaAutoriza'] = $obj_retencion->getfechaAutoriza();
$_SESSION['numeroAutoriza'] = $obj_retencion->getnumeroAutoriza();
$_SESSION['codMsg'] = $obj_retencion->getcodMsg();
$_SESSION['mensaje'] = $obj_retencion->getmensaje();
$_SESSION['msgAdicional'] = $obj_retencion->getmsgAdicional();
$_SESSION['TipoError'] = $obj_retencion->getTipoError();


            }
$db->close();
}

// **********************
// DELETE
// **********************

function delete($id)
{
$db = $this->db->aurora_connect();
$sql = "DELETE FROM retenciones WHERE idRetenciones = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->execute();

$db->close();
}

// **********************
// INSERT
// **********************

function insert()
{
$this->idRetenciones = ""; // clear key for autoincrement
$db = $this->db->aurora_connect();
$sql = "INSERT INTO retenciones ( ambiente,tipoEmision,ruc,claveAcceso,estab,codDoc,punto,sq,fechaEmision,tipoId,nroId,razonSujeto,totalRetencion,codDocSustento,numDocSustento,fechaEmisionDS,periodoFiscal,estado,fechaAutoriza,numeroAutoriza,codMsg,mensaje,msgAdicional,TipoError ) VALUES ( '$this->ambiente','$this->tipoEmision','$this->ruc','$this->claveAcceso','$this->estab','$this->codDoc','$this->punto','$this->sq','$this->fechaEmision','$this->tipoId','$this->nroId','$this->razonSujeto','$this->totalRetencion','$this->codDocSustento','$this->numDocSustento','$this->fechaEmisionDS','$this->periodoFiscal','$this->estado','$this->fechaAutoriza','$this->numeroAutoriza','$this->codMsg','$this->mensaje','$this->msgAdicional','$this->TipoError' )";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
$stmt->execute();

$db->close();
}

// **********************
// UPDATE
// **********************

function update($id)
{

$db = $this->db->aurora_connect();

$sql = " UPDATE retenciones SET  ambiente = '$this->ambiente',tipoEmision = '$this->tipoEmision',ruc = '$this->ruc',claveAcceso = '$this->claveAcceso',estab = '$this->estab',codDoc = '$this->codDoc',punto = '$this->punto',sq = '$this->sq',fechaEmision = '$this->fechaEmision',tipoId = '$this->tipoId',nroId = '$this->nroId',razonSujeto = '$this->razonSujeto',totalRetencion = '$this->totalRetencion',codDocSustento = '$this->codDocSustento',numDocSustento = '$this->numDocSustento',fechaEmisionDS = '$this->fechaEmisionDS',periodoFiscal = '$this->periodoFiscal',estado = '$this->estado',fechaAutoriza = '$this->fechaAutoriza',numeroAutoriza = '$this->numeroAutoriza',codMsg = '$this->codMsg',mensaje = '$this->mensaje',msgAdicional = '$this->msgAdicional',TipoError = '$this->TipoError' WHERE idRetenciones = ? ";

$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->execute();

$db->close();

}


} // class : end

?>
<!-- end of generated class -->
