
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        guia
* GENERATION DATE:  31.07.2015
* CLASS FILE:       C:\wamp\www\genera_clase/generated_classes/class.guia.php
* FOR MYSQL TABLE:  guias
* FOR MYSQL DB:     aurora
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* modify: >> www.aurora-ec.net >> (download for free!)
* -------------------------------------------------------
*
*/
include_once("class.aurora.php");
// **********************
// CLASS DECLARATION
// **********************

class guia
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************


public $idGuias;   // (normal Attribute)
public $numero;   // (normal Attribute)
public $fechaEmision;   // (normal Attribute)
public $ipoIdDestinatario;   // (normal Attribute)
public $numeroIdDestinatario;   // (normal Attribute)
public $razonDestinatario;   // (normal Attribute)
public $estabDestino;   // (normal Attribute)
public $puntoDestino;   // (normal Attribute)
public $dirPartida;   // (normal Attribute)
public $dirDestino;   // (normal Attribute)
public $motivo;   // (normal Attribute)
public $tipoIdTransportista;   // (normal Attribute)
public $numeroIdTransportista;   // (normal Attribute)
public $razonTransportista;   // (normal Attribute)
public $emailTransportista;   // (normal Attribute)
public $telTransportista;   // (normal Attribute)
public $tipoDocRespaldo;   // (normal Attribute)
public $numeroDocRespaldo;   // (normal Attribute)
public $fechaDocRespaldo;   // (normal Attribute)
public $autoDocSustento;   // (normal Attribute)
public $fechaInicioTransporte;   // (normal Attribute)
public $fechaFinTransporte;   // (normal Attribute)
public $ruta;   // (normal Attribute)
public $productos;   // (normal Attribute)
public $embalaje;   // (normal Attribute)
public $placa;   // (normal Attribute)
public $estadoSRI;   // (normal Attribute)
public $claveAcceso;   // (normal Attribute)
public $estadoRow;   // (normal Attribute)
public $fechaAutorizacion;   // (normal Attribute)
public $numeroAutorizacion;   // (normal Attribute)
public $codMsg;   // (normal Attribute)
public $mensaje;   // (normal Attribute)
public $msgAdicional;   // (normal Attribute)
public $tipoError;   // (normal Attribute)

var $db; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function __construct()
{

$this->db = new AuroraDB();
}

function __destruct()
{


}

function genJson_guia($jsonString)
{
$_SESSION['idGuias'] = $jsonString->idGuias;
$_SESSION['numero'] = $jsonString->numero;
$_SESSION['fechaEmision'] = $jsonString->fechaEmision;
$_SESSION['ipoIdDestinatario'] = $jsonString->ipoIdDestinatario;
$_SESSION['numeroIdDestinatario'] = $jsonString->numeroIdDestinatario;
$_SESSION['razonDestinatario'] = $jsonString->razonDestinatario;
$_SESSION['estabDestino'] = $jsonString->estabDestino;
$_SESSION['puntoDestino'] = $jsonString->puntoDestino;
$_SESSION['dirPartida'] = $jsonString->dirPartida;
$_SESSION['dirDestino'] = $jsonString->dirDestino;
$_SESSION['motivo'] = $jsonString->motivo;
$_SESSION['tipoIdTransportista'] = $jsonString->tipoIdTransportista;
$_SESSION['numeroIdTransportista'] = $jsonString->numeroIdTransportista;
$_SESSION['razonTransportista'] = $jsonString->razonTransportista;
$_SESSION['emailTransportista'] = $jsonString->emailTransportista;
$_SESSION['telTransportista'] = $jsonString->telTransportista;
$_SESSION['tipoDocRespaldo'] = $jsonString->tipoDocRespaldo;
$_SESSION['numeroDocRespaldo'] = $jsonString->numeroDocRespaldo;
$_SESSION['fechaDocRespaldo'] = $jsonString->fechaDocRespaldo;
$_SESSION['autoDocSustento'] = $jsonString->autoDocSustento;
$_SESSION['fechaInicioTransporte'] = $jsonString->fechaInicioTransporte;
$_SESSION['fechaFinTransporte'] = $jsonString->fechaFinTransporte;
$_SESSION['ruta'] = $jsonString->ruta;
$_SESSION['productos'] = $jsonString->productos;
$_SESSION['embalaje'] = $jsonString->embalaje;
$_SESSION['placa'] = $jsonString->placa;
$_SESSION['estadoSRI'] = $jsonString->estadoSRI;
$_SESSION['claveAcceso'] = $jsonString->claveAcceso;
$_SESSION['estadoRow'] = $jsonString->estadoRow;
$_SESSION['fechaAutorizacion'] = $jsonString->fechaAutorizacion;
$_SESSION['numeroAutorizacion'] = $jsonString->numeroAutorizacion;
$_SESSION['codMsg'] = $jsonString->codMsg;
$_SESSION['mensaje'] = $jsonString->mensaje;
$_SESSION['msgAdicional'] = $jsonString->msgAdicional;
$_SESSION['tipoError'] = $jsonString->tipoError;

}

function genInsert_guia()
{
$obj_guias->setidGuias($_SESSION['idGuias']);
$obj_guias->setnumero($_SESSION['numero']);
$obj_guias->setfechaEmision($_SESSION['fechaEmision']);
$obj_guias->setipoIdDestinatario($_SESSION['ipoIdDestinatario']);
$obj_guias->setnumeroIdDestinatario($_SESSION['numeroIdDestinatario']);
$obj_guias->setrazonDestinatario($_SESSION['razonDestinatario']);
$obj_guias->setestabDestino($_SESSION['estabDestino']);
$obj_guias->setpuntoDestino($_SESSION['puntoDestino']);
$obj_guias->setdirPartida($_SESSION['dirPartida']);
$obj_guias->setdirDestino($_SESSION['dirDestino']);
$obj_guias->setmotivo($_SESSION['motivo']);
$obj_guias->settipoIdTransportista($_SESSION['tipoIdTransportista']);
$obj_guias->setnumeroIdTransportista($_SESSION['numeroIdTransportista']);
$obj_guias->setrazonTransportista($_SESSION['razonTransportista']);
$obj_guias->setemailTransportista($_SESSION['emailTransportista']);
$obj_guias->settelTransportista($_SESSION['telTransportista']);
$obj_guias->settipoDocRespaldo($_SESSION['tipoDocRespaldo']);
$obj_guias->setnumeroDocRespaldo($_SESSION['numeroDocRespaldo']);
$obj_guias->setfechaDocRespaldo($_SESSION['fechaDocRespaldo']);
$obj_guias->setautoDocSustento($_SESSION['autoDocSustento']);
$obj_guias->setfechaInicioTransporte($_SESSION['fechaInicioTransporte']);
$obj_guias->setfechaFinTransporte($_SESSION['fechaFinTransporte']);
$obj_guias->setruta($_SESSION['ruta']);
$obj_guias->setproductos($_SESSION['productos']);
$obj_guias->setembalaje($_SESSION['embalaje']);
$obj_guias->setplaca($_SESSION['placa']);
$obj_guias->setestadoSRI($_SESSION['estadoSRI']);
$obj_guias->setclaveAcceso($_SESSION['claveAcceso']);
$obj_guias->setestadoRow($_SESSION['estadoRow']);
$obj_guias->setfechaAutorizacion($_SESSION['fechaAutorizacion']);
$obj_guias->setnumeroAutorizacion($_SESSION['numeroAutorizacion']);
$obj_guias->setcodMsg($_SESSION['codMsg']);
$obj_guias->setmensaje($_SESSION['mensaje']);
$obj_guias->setmsgAdicional($_SESSION['msgAdicional']);
$obj_guias->settipoError($_SESSION['tipoError']);

}

// **********************
// GETTER METHODS
// **********************


function getidGuias()
{
return $this->idGuias;
}

function getnumero()
{
return $this->numero;
}

function getfechaEmision()
{
return $this->fechaEmision;
}

function getipoIdDestinatario()
{
return $this->ipoIdDestinatario;
}

function getnumeroIdDestinatario()
{
return $this->numeroIdDestinatario;
}

function getrazonDestinatario()
{
return $this->razonDestinatario;
}

function getestabDestino()
{
return $this->estabDestino;
}

function getpuntoDestino()
{
return $this->puntoDestino;
}

function getdirPartida()
{
return $this->dirPartida;
}

function getdirDestino()
{
return $this->dirDestino;
}

function getmotivo()
{
return $this->motivo;
}

function gettipoIdTransportista()
{
return $this->tipoIdTransportista;
}

function getnumeroIdTransportista()
{
return $this->numeroIdTransportista;
}

function getrazonTransportista()
{
return $this->razonTransportista;
}

function getemailTransportista()
{
return $this->emailTransportista;
}

function gettelTransportista()
{
return $this->telTransportista;
}

function gettipoDocRespaldo()
{
return $this->tipoDocRespaldo;
}

function getnumeroDocRespaldo()
{
return $this->numeroDocRespaldo;
}

function getfechaDocRespaldo()
{
return $this->fechaDocRespaldo;
}

function getautoDocSustento()
{
return $this->autoDocSustento;
}

function getfechaInicioTransporte()
{
return $this->fechaInicioTransporte;
}

function getfechaFinTransporte()
{
return $this->fechaFinTransporte;
}

function getruta()
{
return $this->ruta;
}

function getproductos()
{
return $this->productos;
}

function getembalaje()
{
return $this->embalaje;
}

function getplaca()
{
return $this->placa;
}

function getestadoSRI()
{
return $this->estadoSRI;
}

function getclaveAcceso()
{
return $this->claveAcceso;
}

function getestadoRow()
{
return $this->estadoRow;
}

function getfechaAutorizacion()
{
return $this->fechaAutorizacion;
}

function getnumeroAutorizacion()
{
return $this->numeroAutorizacion;
}

function getcodMsg()
{
return $this->codMsg;
}

function getmensaje()
{
return $this->mensaje;
}

function getmsgAdicional()
{
return $this->msgAdicional;
}

function gettipoError()
{
return $this->tipoError;
}

// **********************
// SETTER METHODS
// **********************


function setidGuias($val)
{
$this->idGuias =  $val;
}

function setnumero($val)
{
$this->numero =  $val;
}

function setfechaEmision($val)
{
$this->fechaEmision =  $val;
}

function setipoIdDestinatario($val)
{
$this->ipoIdDestinatario =  $val;
}

function setnumeroIdDestinatario($val)
{
$this->numeroIdDestinatario =  $val;
}

function setrazonDestinatario($val)
{
$this->razonDestinatario =  $val;
}

function setestabDestino($val)
{
$this->estabDestino =  $val;
}

function setpuntoDestino($val)
{
$this->puntoDestino =  $val;
}

function setdirPartida($val)
{
$this->dirPartida =  $val;
}

function setdirDestino($val)
{
$this->dirDestino =  $val;
}

function setmotivo($val)
{
$this->motivo =  $val;
}

function settipoIdTransportista($val)
{
$this->tipoIdTransportista =  $val;
}

function setnumeroIdTransportista($val)
{
$this->numeroIdTransportista =  $val;
}

function setrazonTransportista($val)
{
$this->razonTransportista =  $val;
}

function setemailTransportista($val)
{
$this->emailTransportista =  $val;
}

function settelTransportista($val)
{
$this->telTransportista =  $val;
}

function settipoDocRespaldo($val)
{
$this->tipoDocRespaldo =  $val;
}

function setnumeroDocRespaldo($val)
{
$this->numeroDocRespaldo =  $val;
}

function setfechaDocRespaldo($val)
{
$this->fechaDocRespaldo =  $val;
}

function setautoDocSustento($val)
{
$this->autoDocSustento =  $val;
}

function setfechaInicioTransporte($val)
{
$this->fechaInicioTransporte =  $val;
}

function setfechaFinTransporte($val)
{
$this->fechaFinTransporte =  $val;
}

function setruta($val)
{
$this->ruta =  $val;
}

function setproductos($val)
{
$this->productos =  $val;
}

function setembalaje($val)
{
$this->embalaje =  $val;
}

function setplaca($val)
{
$this->placa =  $val;
}

function setestadoSRI($val)
{
$this->estadoSRI =  $val;
}

function setclaveAcceso($val)
{
$this->claveAcceso =  $val;
}

function setestadoRow($val)
{
$this->estadoRow =  $val;
}

function setfechaAutorizacion($val)
{
$this->fechaAutorizacion =  $val;
}

function setnumeroAutorizacion($val)
{
$this->numeroAutorizacion =  $val;
}

function setcodMsg($val)
{
$this->codMsg =  $val;
}

function setmensaje($val)
{
$this->mensaje =  $val;
}

function setmsgAdicional($val)
{
$this->msgAdicional =  $val;
}

function settipoError($val)
{
$this->tipoError =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM guias WHERE idGuias = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idGuias, $db_numero, $db_fechaEmision, $db_ipoIdDestinatario, $db_numeroIdDestinatario, $db_razonDestinatario, $db_estabDestino, $db_puntoDestino, $db_dirPartida, $db_dirDestino, $db_motivo, $db_tipoIdTransportista, $db_numeroIdTransportista, $db_razonTransportista, $db_emailTransportista, $db_telTransportista, $db_tipoDocRespaldo, $db_numeroDocRespaldo, $db_fechaDocRespaldo, $db_autoDocSustento, $db_fechaInicioTransporte, $db_fechaFinTransporte, $db_ruta, $db_productos, $db_embalaje, $db_placa, $db_estadoSRI, $db_claveAcceso, $db_estadoRow, $db_fechaAutorizacion, $db_numeroAutorizacion, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_tipoError);
            $stmt->execute();
                if ($stmt->fetch()) {
                $this->idGuias = $db_idGuias;
$this->numero = $db_numero;
$this->fechaEmision = $db_fechaEmision;
$this->ipoIdDestinatario = $db_ipoIdDestinatario;
$this->numeroIdDestinatario = $db_numeroIdDestinatario;
$this->razonDestinatario = $db_razonDestinatario;
$this->estabDestino = $db_estabDestino;
$this->puntoDestino = $db_puntoDestino;
$this->dirPartida = $db_dirPartida;
$this->dirDestino = $db_dirDestino;
$this->motivo = $db_motivo;
$this->tipoIdTransportista = $db_tipoIdTransportista;
$this->numeroIdTransportista = $db_numeroIdTransportista;
$this->razonTransportista = $db_razonTransportista;
$this->emailTransportista = $db_emailTransportista;
$this->telTransportista = $db_telTransportista;
$this->tipoDocRespaldo = $db_tipoDocRespaldo;
$this->numeroDocRespaldo = $db_numeroDocRespaldo;
$this->fechaDocRespaldo = $db_fechaDocRespaldo;
$this->autoDocSustento = $db_autoDocSustento;
$this->fechaInicioTransporte = $db_fechaInicioTransporte;
$this->fechaFinTransporte = $db_fechaFinTransporte;
$this->ruta = $db_ruta;
$this->productos = $db_productos;
$this->embalaje = $db_embalaje;
$this->placa = $db_placa;
$this->estadoSRI = $db_estadoSRI;
$this->claveAcceso = $db_claveAcceso;
$this->estadoRow = $db_estadoRow;
$this->fechaAutorizacion = $db_fechaAutorizacion;
$this->numeroAutorizacion = $db_numeroAutorizacion;
$this->codMsg = $db_codMsg;
$this->mensaje = $db_mensaje;
$this->msgAdicional = $db_msgAdicional;
$this->tipoError = $db_tipoError;


            }
$db->close();
}

// *******************************
// SELECT METHOD / FETCH LOOP
// *******************************

function seleccionar($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM guias WHERE idGuias = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idGuias, $db_numero, $db_fechaEmision, $db_ipoIdDestinatario, $db_numeroIdDestinatario, $db_razonDestinatario, $db_estabDestino, $db_puntoDestino, $db_dirPartida, $db_dirDestino, $db_motivo, $db_tipoIdTransportista, $db_numeroIdTransportista, $db_razonTransportista, $db_emailTransportista, $db_telTransportista, $db_tipoDocRespaldo, $db_numeroDocRespaldo, $db_fechaDocRespaldo, $db_autoDocSustento, $db_fechaInicioTransporte, $db_fechaFinTransporte, $db_ruta, $db_productos, $db_embalaje, $db_placa, $db_estadoSRI, $db_claveAcceso, $db_estadoRow, $db_fechaAutorizacion, $db_numeroAutorizacion, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_tipoError);
            $stmt->execute();
                while ($stmt->fetch()) {
                $obj_guias->idGuias = $db_idGuias;
$obj_guias->numero = $db_numero;
$obj_guias->fechaEmision = $db_fechaEmision;
$obj_guias->ipoIdDestinatario = $db_ipoIdDestinatario;
$obj_guias->numeroIdDestinatario = $db_numeroIdDestinatario;
$obj_guias->razonDestinatario = $db_razonDestinatario;
$obj_guias->estabDestino = $db_estabDestino;
$obj_guias->puntoDestino = $db_puntoDestino;
$obj_guias->dirPartida = $db_dirPartida;
$obj_guias->dirDestino = $db_dirDestino;
$obj_guias->motivo = $db_motivo;
$obj_guias->tipoIdTransportista = $db_tipoIdTransportista;
$obj_guias->numeroIdTransportista = $db_numeroIdTransportista;
$obj_guias->razonTransportista = $db_razonTransportista;
$obj_guias->emailTransportista = $db_emailTransportista;
$obj_guias->telTransportista = $db_telTransportista;
$obj_guias->tipoDocRespaldo = $db_tipoDocRespaldo;
$obj_guias->numeroDocRespaldo = $db_numeroDocRespaldo;
$obj_guias->fechaDocRespaldo = $db_fechaDocRespaldo;
$obj_guias->autoDocSustento = $db_autoDocSustento;
$obj_guias->fechaInicioTransporte = $db_fechaInicioTransporte;
$obj_guias->fechaFinTransporte = $db_fechaFinTransporte;
$obj_guias->ruta = $db_ruta;
$obj_guias->productos = $db_productos;
$obj_guias->embalaje = $db_embalaje;
$obj_guias->placa = $db_placa;
$obj_guias->estadoSRI = $db_estadoSRI;
$obj_guias->claveAcceso = $db_claveAcceso;
$obj_guias->estadoRow = $db_estadoRow;
$obj_guias->fechaAutorizacion = $db_fechaAutorizacion;
$obj_guias->numeroAutorizacion = $db_numeroAutorizacion;
$obj_guias->codMsg = $db_codMsg;
$obj_guias->mensaje = $db_mensaje;
$obj_guias->msgAdicional = $db_msgAdicional;
$obj_guias->tipoError = $db_tipoError;


            }
$db->close();
}

// *******************************
// SELECT METHOD / FETCH LOOP
// *******************************

function recorrer($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM guias WHERE idGuias = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idGuias, $db_numero, $db_fechaEmision, $db_ipoIdDestinatario, $db_numeroIdDestinatario, $db_razonDestinatario, $db_estabDestino, $db_puntoDestino, $db_dirPartida, $db_dirDestino, $db_motivo, $db_tipoIdTransportista, $db_numeroIdTransportista, $db_razonTransportista, $db_emailTransportista, $db_telTransportista, $db_tipoDocRespaldo, $db_numeroDocRespaldo, $db_fechaDocRespaldo, $db_autoDocSustento, $db_fechaInicioTransporte, $db_fechaFinTransporte, $db_ruta, $db_productos, $db_embalaje, $db_placa, $db_estadoSRI, $db_claveAcceso, $db_estadoRow, $db_fechaAutorizacion, $db_numeroAutorizacion, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_tipoError);
            $stmt->execute();
                if ($stmt->fetch()) {
                $_SESSION['idGuias'] = $obj_guias->getidGuias();
$_SESSION['numero'] = $obj_guias->getnumero();
$_SESSION['fechaEmision'] = $obj_guias->getfechaEmision();
$_SESSION['ipoIdDestinatario'] = $obj_guias->getipoIdDestinatario();
$_SESSION['numeroIdDestinatario'] = $obj_guias->getnumeroIdDestinatario();
$_SESSION['razonDestinatario'] = $obj_guias->getrazonDestinatario();
$_SESSION['estabDestino'] = $obj_guias->getestabDestino();
$_SESSION['puntoDestino'] = $obj_guias->getpuntoDestino();
$_SESSION['dirPartida'] = $obj_guias->getdirPartida();
$_SESSION['dirDestino'] = $obj_guias->getdirDestino();
$_SESSION['motivo'] = $obj_guias->getmotivo();
$_SESSION['tipoIdTransportista'] = $obj_guias->gettipoIdTransportista();
$_SESSION['numeroIdTransportista'] = $obj_guias->getnumeroIdTransportista();
$_SESSION['razonTransportista'] = $obj_guias->getrazonTransportista();
$_SESSION['emailTransportista'] = $obj_guias->getemailTransportista();
$_SESSION['telTransportista'] = $obj_guias->gettelTransportista();
$_SESSION['tipoDocRespaldo'] = $obj_guias->gettipoDocRespaldo();
$_SESSION['numeroDocRespaldo'] = $obj_guias->getnumeroDocRespaldo();
$_SESSION['fechaDocRespaldo'] = $obj_guias->getfechaDocRespaldo();
$_SESSION['autoDocSustento'] = $obj_guias->getautoDocSustento();
$_SESSION['fechaInicioTransporte'] = $obj_guias->getfechaInicioTransporte();
$_SESSION['fechaFinTransporte'] = $obj_guias->getfechaFinTransporte();
$_SESSION['ruta'] = $obj_guias->getruta();
$_SESSION['productos'] = $obj_guias->getproductos();
$_SESSION['embalaje'] = $obj_guias->getembalaje();
$_SESSION['placa'] = $obj_guias->getplaca();
$_SESSION['estadoSRI'] = $obj_guias->getestadoSRI();
$_SESSION['claveAcceso'] = $obj_guias->getclaveAcceso();
$_SESSION['estadoRow'] = $obj_guias->getestadoRow();
$_SESSION['fechaAutorizacion'] = $obj_guias->getfechaAutorizacion();
$_SESSION['numeroAutorizacion'] = $obj_guias->getnumeroAutorizacion();
$_SESSION['codMsg'] = $obj_guias->getcodMsg();
$_SESSION['mensaje'] = $obj_guias->getmensaje();
$_SESSION['msgAdicional'] = $obj_guias->getmsgAdicional();
$_SESSION['tipoError'] = $obj_guias->gettipoError();


            }
$db->close();
}

// **********************
// DELETE
// **********************

function delete($id)
{
$db = $this->db->aurora_connect();
$sql = "DELETE FROM guias WHERE idGuias = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->execute();

$db->close();
}

// **********************
// INSERT
// **********************

function insert()
{
$this->idGuias = ""; // clear key for autoincrement
$db = $this->db->aurora_connect();
$sql = "INSERT INTO guias ( numero,fechaEmision,ipoIdDestinatario,numeroIdDestinatario,razonDestinatario,estabDestino,puntoDestino,dirPartida,dirDestino,motivo,tipoIdTransportista,numeroIdTransportista,razonTransportista,emailTransportista,telTransportista,tipoDocRespaldo,numeroDocRespaldo,fechaDocRespaldo,autoDocSustento,fechaInicioTransporte,fechaFinTransporte,ruta,productos,embalaje,placa,estadoSRI,claveAcceso,estadoRow,fechaAutorizacion,numeroAutorizacion,codMsg,mensaje,msgAdicional,tipoError ) VALUES ( '$this->numero','$this->fechaEmision','$this->ipoIdDestinatario','$this->numeroIdDestinatario','$this->razonDestinatario','$this->estabDestino','$this->puntoDestino','$this->dirPartida','$this->dirDestino','$this->motivo','$this->tipoIdTransportista','$this->numeroIdTransportista','$this->razonTransportista','$this->emailTransportista','$this->telTransportista','$this->tipoDocRespaldo','$this->numeroDocRespaldo','$this->fechaDocRespaldo','$this->autoDocSustento','$this->fechaInicioTransporte','$this->fechaFinTransporte','$this->ruta','$this->productos','$this->embalaje','$this->placa','$this->estadoSRI','$this->claveAcceso','$this->estadoRow','$this->fechaAutorizacion','$this->numeroAutorizacion','$this->codMsg','$this->mensaje','$this->msgAdicional','$this->tipoError' )";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
$stmt->execute();

$db->close();
}

// **********************
// UPDATE
// **********************

function update($id)
{

$db = $this->db->aurora_connect();

$sql = " UPDATE guias SET  numero = '$this->numero',fechaEmision = '$this->fechaEmision',ipoIdDestinatario = '$this->ipoIdDestinatario',numeroIdDestinatario = '$this->numeroIdDestinatario',razonDestinatario = '$this->razonDestinatario',estabDestino = '$this->estabDestino',puntoDestino = '$this->puntoDestino',dirPartida = '$this->dirPartida',dirDestino = '$this->dirDestino',motivo = '$this->motivo',tipoIdTransportista = '$this->tipoIdTransportista',numeroIdTransportista = '$this->numeroIdTransportista',razonTransportista = '$this->razonTransportista',emailTransportista = '$this->emailTransportista',telTransportista = '$this->telTransportista',tipoDocRespaldo = '$this->tipoDocRespaldo',numeroDocRespaldo = '$this->numeroDocRespaldo',fechaDocRespaldo = '$this->fechaDocRespaldo',autoDocSustento = '$this->autoDocSustento',fechaInicioTransporte = '$this->fechaInicioTransporte',fechaFinTransporte = '$this->fechaFinTransporte',ruta = '$this->ruta',productos = '$this->productos',embalaje = '$this->embalaje',placa = '$this->placa',estadoSRI = '$this->estadoSRI',claveAcceso = '$this->claveAcceso',estadoRow = '$this->estadoRow',fechaAutorizacion = '$this->fechaAutorizacion',numeroAutorizacion = '$this->numeroAutorizacion',codMsg = '$this->codMsg',mensaje = '$this->mensaje',msgAdicional = '$this->msgAdicional',tipoError = '$this->tipoError' WHERE idGuias = ? ";

$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->execute();

$db->close();

}


} // class : end

?>
<!-- end of generated class -->
