
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        factura
* GENERATION DATE:  23.07.2015
* CLASS FILE:       C:\wamp\www\genera_clase/generated_classes/class.factura.php
* FOR MYSQL TABLE:  facturas
* FOR MYSQL DB:     aurora
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* modify: >> www.aurora-ec.net >> (download for free!)
* -------------------------------------------------------
*
*/
include_once("class.aurora.php");
// **********************
// CLASS DECLARATION
// **********************

class factura
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************


public $idFacturas;   // (normal Attribute)
public $ambiente;   // (normal Attribute)
public $tipoEmision;   // (normal Attribute)
public $ruc;   // (normal Attribute)
public $claveAcceso;   // (normal Attribute)
public $estab;   // (normal Attribute)
public $codDoc;   // (normal Attribute)
public $punto;   // (normal Attribute)
public $sq;   // (normal Attribute)
public $fechaEmision;   // (normal Attribute)
public $tipoId;   // (normal Attribute)
public $nroId;   // (normal Attribute)
public $guia;   // (normal Attribute)
public $razonComprador;   // (normal Attribute)
public $importeSinImpuesto;   // (normal Attribute)
public $totalImpto;   // (normal Attribute)
public $propina;   // (normal Attribute)
public $importeTotal;   // (normal Attribute)
public $moneda;   // (normal Attribute)
public $estado;   // (normal Attribute)
public $fechaAutoriza;   // (normal Attribute)
public $numeroAutoriza;   // (normal Attribute)
public $codMsg;   // (normal Attribute)
public $mensaje;   // (normal Attribute)
public $msgAdicional;   // (normal Attribute)
public $tipoError;   // (normal Attribute)

var $db; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function __construct()
{

$this->db = new AuroraDB();
}

function __destruct()
{


}

function genJson_factura($jsonString)
{
$_SESSION['idFacturas'] = $jsonString->idFacturas;
$_SESSION['ambiente'] = $jsonString->ambiente;
$_SESSION['tipoEmision'] = $jsonString->tipoEmision;
$_SESSION['ruc'] = $jsonString->ruc;
$_SESSION['claveAcceso'] = $jsonString->claveAcceso;
$_SESSION['estab'] = $jsonString->estab;
$_SESSION['codDoc'] = $jsonString->codDoc;
$_SESSION['punto'] = $jsonString->punto;
$_SESSION['sq'] = $jsonString->sq;
$_SESSION['fechaEmision'] = $jsonString->fechaEmision;
$_SESSION['tipoId'] = $jsonString->tipoId;
$_SESSION['nroId'] = $jsonString->nroId;
$_SESSION['guia'] = $jsonString->guia;
$_SESSION['razonComprador'] = $jsonString->razonComprador;
$_SESSION['importeSinImpuesto'] = $jsonString->importeSinImpuesto;
$_SESSION['totalImpto'] = $jsonString->totalImpto;
$_SESSION['propina'] = $jsonString->propina;
$_SESSION['importeTotal'] = $jsonString->importeTotal;
$_SESSION['moneda'] = $jsonString->moneda;
$_SESSION['estado'] = $jsonString->estado;
$_SESSION['fechaAutoriza'] = $jsonString->fechaAutoriza;
$_SESSION['numeroAutoriza'] = $jsonString->numeroAutoriza;
$_SESSION['codMsg'] = $jsonString->codMsg;
$_SESSION['mensaje'] = $jsonString->mensaje;
$_SESSION['msgAdicional'] = $jsonString->msgAdicional;
$_SESSION['tipoError'] = $jsonString->tipoError;

}

function genInsert_factura()
{
$obj_factura->setidFacturas($_SESSION['idFacturas']);
$obj_factura->setambiente($_SESSION['ambiente']);
$obj_factura->settipoEmision($_SESSION['tipoEmision']);
$obj_factura->setruc($_SESSION['ruc']);
$obj_factura->setclaveAcceso($_SESSION['claveAcceso']);
$obj_factura->setestab($_SESSION['estab']);
$obj_factura->setcodDoc($_SESSION['codDoc']);
$obj_factura->setpunto($_SESSION['punto']);
$obj_factura->setsq($_SESSION['sq']);
$obj_factura->setfechaEmision($_SESSION['fechaEmision']);
$obj_factura->settipoId($_SESSION['tipoId']);
$obj_factura->setnroId($_SESSION['nroId']);
$obj_factura->setguia($_SESSION['guia']);
$obj_factura->setrazonComprador($_SESSION['razonComprador']);
$obj_factura->setimporteSinImpuesto($_SESSION['importeSinImpuesto']);
$obj_factura->settotalImpto($_SESSION['totalImpto']);
$obj_factura->setpropina($_SESSION['propina']);
$obj_factura->setimporteTotal($_SESSION['importeTotal']);
$obj_factura->setmoneda($_SESSION['moneda']);
$obj_factura->setestado($_SESSION['estado']);
$obj_factura->setfechaAutoriza($_SESSION['fechaAutoriza']);
$obj_factura->setnumeroAutoriza($_SESSION['numeroAutoriza']);
$obj_factura->setcodMsg($_SESSION['codMsg']);
$obj_factura->setmensaje($_SESSION['mensaje']);
$obj_factura->setmsgAdicional($_SESSION['msgAdicional']);
$obj_factura->settipoError($_SESSION['tipoError']);

}

// **********************
// GETTER METHODS
// **********************


function getidFacturas()
{
return $this->idFacturas;
}

function getambiente()
{
return $this->ambiente;
}

function gettipoEmision()
{
return $this->tipoEmision;
}

function getruc()
{
return $this->ruc;
}

function getclaveAcceso()
{
return $this->claveAcceso;
}

function getestab()
{
return $this->estab;
}

function getcodDoc()
{
return $this->codDoc;
}

function getpunto()
{
return $this->punto;
}

function getsq()
{
return $this->sq;
}

function getfechaEmision()
{
return $this->fechaEmision;
}

function gettipoId()
{
return $this->tipoId;
}

function getnroId()
{
return $this->nroId;
}

function getguia()
{
return $this->guia;
}

function getrazonComprador()
{
return $this->razonComprador;
}

function getimporteSinImpuesto()
{
return $this->importeSinImpuesto;
}

function gettotalImpto()
{
return $this->totalImpto;
}

function getpropina()
{
return $this->propina;
}

function getimporteTotal()
{
return $this->importeTotal;
}

function getmoneda()
{
return $this->moneda;
}

function getestado()
{
return $this->estado;
}

function getfechaAutoriza()
{
return $this->fechaAutoriza;
}

function getnumeroAutoriza()
{
return $this->numeroAutoriza;
}

function getcodMsg()
{
return $this->codMsg;
}

function getmensaje()
{
return $this->mensaje;
}

function getmsgAdicional()
{
return $this->msgAdicional;
}

function gettipoError()
{
return $this->tipoError;
}

// **********************
// SETTER METHODS
// **********************


function setidFacturas($val)
{
$this->idFacturas =  $val;
}

function setambiente($val)
{
$this->ambiente =  $val;
}

function settipoEmision($val)
{
$this->tipoEmision =  $val;
}

function setruc($val)
{
$this->ruc =  $val;
}

function setclaveAcceso($val)
{
$this->claveAcceso =  $val;
}

function setestab($val)
{
$this->estab =  $val;
}

function setcodDoc($val)
{
$this->codDoc =  $val;
}

function setpunto($val)
{
$this->punto =  $val;
}

function setsq($val)
{
$this->sq =  $val;
}

function setfechaEmision($val)
{
$this->fechaEmision =  $val;
}

function settipoId($val)
{
$this->tipoId =  $val;
}

function setnroId($val)
{
$this->nroId =  $val;
}

function setguia($val)
{
$this->guia =  $val;
}

function setrazonComprador($val)
{
$this->razonComprador =  $val;
}

function setimporteSinImpuesto($val)
{
$this->importeSinImpuesto =  $val;
}

function settotalImpto($val)
{
$this->totalImpto =  $val;
}

function setpropina($val)
{
$this->propina =  $val;
}

function setimporteTotal($val)
{
$this->importeTotal =  $val;
}

function setmoneda($val)
{
$this->moneda =  $val;
}

function setestado($val)
{
$this->estado =  $val;
}

function setfechaAutoriza($val)
{
$this->fechaAutoriza =  $val;
}

function setnumeroAutoriza($val)
{
$this->numeroAutoriza =  $val;
}

function setcodMsg($val)
{
$this->codMsg =  $val;
}

function setmensaje($val)
{
$this->mensaje =  $val;
}

function setmsgAdicional($val)
{
$this->msgAdicional =  $val;
}

function settipoError($val)
{
$this->tipoError =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM facturas WHERE idFacturas = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idFacturas, $db_ambiente, $db_tipoEmision, $db_ruc, $db_claveAcceso, $db_estab, $db_codDoc, $db_punto, $db_sq, $db_fechaEmision, $db_tipoId, $db_nroId, $db_guia, $db_razonComprador, $db_importeSinImpuesto, $db_totalImpto, $db_propina, $db_importeTotal, $db_moneda, $db_estado, $db_fechaAutoriza, $db_numeroAutoriza, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_tipoError);
            $stmt->execute();
                if ($stmt->fetch()) {
                $this->idFacturas = $db_idFacturas;
$this->ambiente = $db_ambiente;
$this->tipoEmision = $db_tipoEmision;
$this->ruc = $db_ruc;
$this->claveAcceso = $db_claveAcceso;
$this->estab = $db_estab;
$this->codDoc = $db_codDoc;
$this->punto = $db_punto;
$this->sq = $db_sq;
$this->fechaEmision = $db_fechaEmision;
$this->tipoId = $db_tipoId;
$this->nroId = $db_nroId;
$this->guia = $db_guia;
$this->razonComprador = $db_razonComprador;
$this->importeSinImpuesto = $db_importeSinImpuesto;
$this->totalImpto = $db_totalImpto;
$this->propina = $db_propina;
$this->importeTotal = $db_importeTotal;
$this->moneda = $db_moneda;
$this->estado = $db_estado;
$this->fechaAutoriza = $db_fechaAutoriza;
$this->numeroAutoriza = $db_numeroAutoriza;
$this->codMsg = $db_codMsg;
$this->mensaje = $db_mensaje;
$this->msgAdicional = $db_msgAdicional;
$this->tipoError = $db_tipoError;


            }
$db->close();
}

// *******************************
// SELECT METHOD / FETCH LOOP
// *******************************

function seleccionar($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM facturas WHERE idFacturas = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idFacturas, $db_ambiente, $db_tipoEmision, $db_ruc, $db_claveAcceso, $db_estab, $db_codDoc, $db_punto, $db_sq, $db_fechaEmision, $db_tipoId, $db_nroId, $db_guia, $db_razonComprador, $db_importeSinImpuesto, $db_totalImpto, $db_propina, $db_importeTotal, $db_moneda, $db_estado, $db_fechaAutoriza, $db_numeroAutoriza, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_tipoError);
            $stmt->execute();
                while ($stmt->fetch()) {
                $obj_factura->idFacturas = $db_idFacturas;
$obj_factura->ambiente = $db_ambiente;
$obj_factura->tipoEmision = $db_tipoEmision;
$obj_factura->ruc = $db_ruc;
$obj_factura->claveAcceso = $db_claveAcceso;
$obj_factura->estab = $db_estab;
$obj_factura->codDoc = $db_codDoc;
$obj_factura->punto = $db_punto;
$obj_factura->sq = $db_sq;
$obj_factura->fechaEmision = $db_fechaEmision;
$obj_factura->tipoId = $db_tipoId;
$obj_factura->nroId = $db_nroId;
$obj_factura->guia = $db_guia;
$obj_factura->razonComprador = $db_razonComprador;
$obj_factura->importeSinImpuesto = $db_importeSinImpuesto;
$obj_factura->totalImpto = $db_totalImpto;
$obj_factura->propina = $db_propina;
$obj_factura->importeTotal = $db_importeTotal;
$obj_factura->moneda = $db_moneda;
$obj_factura->estado = $db_estado;
$obj_factura->fechaAutoriza = $db_fechaAutoriza;
$obj_factura->numeroAutoriza = $db_numeroAutoriza;
$obj_factura->codMsg = $db_codMsg;
$obj_factura->mensaje = $db_mensaje;
$obj_factura->msgAdicional = $db_msgAdicional;
$obj_factura->tipoError = $db_tipoError;


            }
$db->close();
}

// *******************************
// SELECT METHOD / FETCH LOOP
// *******************************

function recorrer($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM facturas WHERE idFacturas = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_idFacturas, $db_ambiente, $db_tipoEmision, $db_ruc, $db_claveAcceso, $db_estab, $db_codDoc, $db_punto, $db_sq, $db_fechaEmision, $db_tipoId, $db_nroId, $db_guia, $db_razonComprador, $db_importeSinImpuesto, $db_totalImpto, $db_propina, $db_importeTotal, $db_moneda, $db_estado, $db_fechaAutoriza, $db_numeroAutoriza, $db_codMsg, $db_mensaje, $db_msgAdicional, $db_tipoError);
            $stmt->execute();
                if ($stmt->fetch()) {
                $_SESSION['idFacturas'] = $obj_factura->getidFacturas();
$_SESSION['ambiente'] = $obj_factura->getambiente();
$_SESSION['tipoEmision'] = $obj_factura->gettipoEmision();
$_SESSION['ruc'] = $obj_factura->getruc();
$_SESSION['claveAcceso'] = $obj_factura->getclaveAcceso();
$_SESSION['estab'] = $obj_factura->getestab();
$_SESSION['codDoc'] = $obj_factura->getcodDoc();
$_SESSION['punto'] = $obj_factura->getpunto();
$_SESSION['sq'] = $obj_factura->getsq();
$_SESSION['fechaEmision'] = $obj_factura->getfechaEmision();
$_SESSION['tipoId'] = $obj_factura->gettipoId();
$_SESSION['nroId'] = $obj_factura->getnroId();
$_SESSION['guia'] = $obj_factura->getguia();
$_SESSION['razonComprador'] = $obj_factura->getrazonComprador();
$_SESSION['importeSinImpuesto'] = $obj_factura->getimporteSinImpuesto();
$_SESSION['totalImpto'] = $obj_factura->gettotalImpto();
$_SESSION['propina'] = $obj_factura->getpropina();
$_SESSION['importeTotal'] = $obj_factura->getimporteTotal();
$_SESSION['moneda'] = $obj_factura->getmoneda();
$_SESSION['estado'] = $obj_factura->getestado();
$_SESSION['fechaAutoriza'] = $obj_factura->getfechaAutoriza();
$_SESSION['numeroAutoriza'] = $obj_factura->getnumeroAutoriza();
$_SESSION['codMsg'] = $obj_factura->getcodMsg();
$_SESSION['mensaje'] = $obj_factura->getmensaje();
$_SESSION['msgAdicional'] = $obj_factura->getmsgAdicional();
$_SESSION['tipoError'] = $obj_factura->gettipoError();


            }
$db->close();
}

// **********************
// DELETE
// **********************

function delete($id)
{
$db = $this->db->aurora_connect();
$sql = "DELETE FROM facturas WHERE idFacturas = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->execute();

$db->close();
}

// **********************
// INSERT
// **********************

function insert()
{
$this->idFacturas = ""; // clear key for autoincrement
$db = $this->db->aurora_connect();
$sql = "INSERT INTO facturas ( ambiente,tipoEmision,ruc,claveAcceso,estab,codDoc,punto,sq,fechaEmision,tipoId,nroId,guia,razonComprador,importeSinImpuesto,totalImpto,propina,importeTotal,moneda,estado,fechaAutoriza,numeroAutoriza,codMsg,mensaje,msgAdicional,tipoError ) VALUES ( '$this->ambiente','$this->tipoEmision','$this->ruc','$this->claveAcceso','$this->estab','$this->codDoc','$this->punto','$this->sq','$this->fechaEmision','$this->tipoId','$this->nroId','$this->guia','$this->razonComprador','$this->importeSinImpuesto','$this->totalImpto','$this->propina','$this->importeTotal','$this->moneda','$this->estado','$this->fechaAutoriza','$this->numeroAutoriza','$this->codMsg','$this->mensaje','$this->msgAdicional','$this->tipoError' )";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
$stmt->execute();

$db->close();
}

// **********************
// UPDATE
// **********************

function update($id)
{

$db = $this->db->aurora_connect();

$sql = " UPDATE facturas SET  ambiente = '$this->ambiente',tipoEmision = '$this->tipoEmision',ruc = '$this->ruc',claveAcceso = '$this->claveAcceso',estab = '$this->estab',codDoc = '$this->codDoc',punto = '$this->punto',sq = '$this->sq',fechaEmision = '$this->fechaEmision',tipoId = '$this->tipoId',nroId = '$this->nroId',guia = '$this->guia',razonComprador = '$this->razonComprador',importeSinImpuesto = '$this->importeSinImpuesto',totalImpto = '$this->totalImpto',propina = '$this->propina',importeTotal = '$this->importeTotal',moneda = '$this->moneda',estado = '$this->estado',fechaAutoriza = '$this->fechaAutoriza',numeroAutoriza = '$this->numeroAutoriza',codMsg = '$this->codMsg',mensaje = '$this->mensaje',msgAdicional = '$this->msgAdicional',tipoError = '$this->tipoError' WHERE idFacturas = ? ";

$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->execute();

$db->close();

}


} // class : end

?>
<!-- end of generated class -->
