
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        bill
* GENERATION DATE:  19.09.2017
* CLASS FILE:       C:\wamp64\www\genera_clase/generated_classes/class.bill.php
* FOR MYSQL TABLE:  bill
* FOR MYSQL DB:     dbaurora
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* modify: >> www.aurora-ec.net >> (download for free!)
* -------------------------------------------------------
*
*/
include_once("../resources/class.aurora.php");
// **********************
// CLASS DECLARATION
// **********************

class bill
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************


public $TxnID;   // (normal Attribute)
public $TimeCreated;   // (normal Attribute)
public $TimeModified;   // (normal Attribute)
public $EditSequence;   // (normal Attribute)
public $TxnNumber;   // (normal Attribute)
public $VendorRef_ListID;   // (normal Attribute)
public $VendorRef_FullName;   // (normal Attribute)
public $VendorAddress_Addr1;   // (normal Attribute)
public $VendorAddress_Addr2;   // (normal Attribute)
public $VendorAddress_Addr3;   // (normal Attribute)
public $VendorAddress_Addr4;   // (normal Attribute)
public $VendorAddress_Addr5;   // (normal Attribute)
public $VendorAddress_City;   // (normal Attribute)
public $VendorAddress_State;   // (normal Attribute)
public $VendorAddress_PostalCode;   // (normal Attribute)
public $VendorAddress_Country;   // (normal Attribute)
public $VendorAddress_Note;   // (normal Attribute)
public $APAccountRef_ListID;   // (normal Attribute)
public $APAccountRef_FullName;   // (normal Attribute)
public $TxnDate;   // (normal Attribute)
public $DueDate;   // (normal Attribute)
public $AmountDue;   // (normal Attribute)
public $CurrencyRef_ListID;   // (normal Attribute)
public $CurrencyRef_FullName;   // (normal Attribute)
public $ExchangeRate;   // (normal Attribute)
public $AmountDueInHomeCurrency;   // (normal Attribute)
public $RefNumber;   // (normal Attribute)
public $TermsRef_ListID;   // (normal Attribute)
public $TermsRef_FullName;   // (normal Attribute)
public $Memo;   // (normal Attribute)
public $IsTaxIncluded;   // (normal Attribute)
public $SalesTaxCodeRef_ListID;   // (normal Attribute)
public $SalesTaxCodeRef_FullName;   // (normal Attribute)
public $IsPaID;   // (normal Attribute)
public $OpenAmount;   // (normal Attribute)
public $CustomField1;   // (normal Attribute)
public $CustomField2;   // (normal Attribute)
public $CustomField3;   // (normal Attribute)
public $CustomField4;   // (normal Attribute)
public $CustomField5;   // (normal Attribute)
public $CustomField6;   // (normal Attribute)
public $CustomField7;   // (normal Attribute)
public $CustomField8;   // (normal Attribute)
public $CustomField9;   // (normal Attribute)
public $CustomField10;   // (normal Attribute)
public $CustomField11;   // (normal Attribute)
public $CustomField12;   // (normal Attribute)
public $CustomField13;   // (normal Attribute)
public $CustomField14;   // (normal Attribute)
public $CustomField15;   // (normal Attribute)
public $Status;   // (normal Attribute)

var $db; // Instance of class database
var $estado; 


// **********************
// CONSTRUCTOR METHOD
// **********************

function __construct()
{

$this->db = conecta_PDO();
}

function __destruct()
{


}

function genJson_bill($jsonString)
{
$_SESSION['bill']['TxnID'] = $jsonString->TxnID;
$_SESSION['bill']['TimeCreated'] = $jsonString->TimeCreated;
$_SESSION['bill']['TimeModified'] = $jsonString->TimeModified;
$_SESSION['bill']['EditSequence'] = $jsonString->EditSequence;
$_SESSION['bill']['TxnNumber'] = $jsonString->TxnNumber;
$_SESSION['bill']['VendorRef_ListID'] = $jsonString->VendorRef_ListID;
$_SESSION['bill']['VendorRef_FullName'] = $jsonString->VendorRef_FullName;
$_SESSION['bill']['VendorAddress_Addr1'] = $jsonString->VendorAddress_Addr1;
$_SESSION['bill']['VendorAddress_Addr2'] = $jsonString->VendorAddress_Addr2;
$_SESSION['bill']['VendorAddress_Addr3'] = $jsonString->VendorAddress_Addr3;
$_SESSION['bill']['VendorAddress_Addr4'] = $jsonString->VendorAddress_Addr4;
$_SESSION['bill']['VendorAddress_Addr5'] = $jsonString->VendorAddress_Addr5;
$_SESSION['bill']['VendorAddress_City'] = $jsonString->VendorAddress_City;
$_SESSION['bill']['VendorAddress_State'] = $jsonString->VendorAddress_State;
$_SESSION['bill']['VendorAddress_PostalCode'] = $jsonString->VendorAddress_PostalCode;
$_SESSION['bill']['VendorAddress_Country'] = $jsonString->VendorAddress_Country;
$_SESSION['bill']['VendorAddress_Note'] = $jsonString->VendorAddress_Note;
$_SESSION['bill']['APAccountRef_ListID'] = $jsonString->APAccountRef_ListID;
$_SESSION['bill']['APAccountRef_FullName'] = $jsonString->APAccountRef_FullName;
$_SESSION['bill']['TxnDate'] = $jsonString->TxnDate;
$_SESSION['bill']['DueDate'] = $jsonString->DueDate;
$_SESSION['bill']['AmountDue'] = $jsonString->AmountDue;
$_SESSION['bill']['CurrencyRef_ListID'] = $jsonString->CurrencyRef_ListID;
$_SESSION['bill']['CurrencyRef_FullName'] = $jsonString->CurrencyRef_FullName;
$_SESSION['bill']['ExchangeRate'] = $jsonString->ExchangeRate;
$_SESSION['bill']['AmountDueInHomeCurrency'] = $jsonString->AmountDueInHomeCurrency;
$_SESSION['bill']['RefNumber'] = $jsonString->RefNumber;
$_SESSION['bill']['TermsRef_ListID'] = $jsonString->TermsRef_ListID;
$_SESSION['bill']['TermsRef_FullName'] = $jsonString->TermsRef_FullName;
$_SESSION['bill']['Memo'] = $jsonString->Memo;
$_SESSION['bill']['IsTaxIncluded'] = $jsonString->IsTaxIncluded;
$_SESSION['bill']['SalesTaxCodeRef_ListID'] = $jsonString->SalesTaxCodeRef_ListID;
$_SESSION['bill']['SalesTaxCodeRef_FullName'] = $jsonString->SalesTaxCodeRef_FullName;
$_SESSION['bill']['IsPaID'] = $jsonString->IsPaID;
$_SESSION['bill']['OpenAmount'] = $jsonString->OpenAmount;
$_SESSION['bill']['CustomField1'] = $jsonString->CustomField1;
$_SESSION['bill']['CustomField2'] = $jsonString->CustomField2;
$_SESSION['bill']['CustomField3'] = $jsonString->CustomField3;
$_SESSION['bill']['CustomField4'] = $jsonString->CustomField4;
$_SESSION['bill']['CustomField5'] = $jsonString->CustomField5;
$_SESSION['bill']['CustomField6'] = $jsonString->CustomField6;
$_SESSION['bill']['CustomField7'] = $jsonString->CustomField7;
$_SESSION['bill']['CustomField8'] = $jsonString->CustomField8;
$_SESSION['bill']['CustomField9'] = $jsonString->CustomField9;
$_SESSION['bill']['CustomField10'] = $jsonString->CustomField10;
$_SESSION['bill']['CustomField11'] = $jsonString->CustomField11;
$_SESSION['bill']['CustomField12'] = $jsonString->CustomField12;
$_SESSION['bill']['CustomField13'] = $jsonString->CustomField13;
$_SESSION['bill']['CustomField14'] = $jsonString->CustomField14;
$_SESSION['bill']['CustomField15'] = $jsonString->CustomField15;
$_SESSION['bill']['Status'] = $jsonString->Status;

}

function genInsert_bill()
{
$this->setTxnID($_SESSION['bill']['TxnID']);
$this->setTimeCreated($_SESSION['bill']['TimeCreated']);
$this->setTimeModified($_SESSION['bill']['TimeModified']);
$this->setEditSequence($_SESSION['bill']['EditSequence']);
$this->setTxnNumber($_SESSION['bill']['TxnNumber']);
$this->setVendorRef_ListID($_SESSION['bill']['VendorRef_ListID']);
$this->setVendorRef_FullName($_SESSION['bill']['VendorRef_FullName']);
$this->setVendorAddress_Addr1($_SESSION['bill']['VendorAddress_Addr1']);
$this->setVendorAddress_Addr2($_SESSION['bill']['VendorAddress_Addr2']);
$this->setVendorAddress_Addr3($_SESSION['bill']['VendorAddress_Addr3']);
$this->setVendorAddress_Addr4($_SESSION['bill']['VendorAddress_Addr4']);
$this->setVendorAddress_Addr5($_SESSION['bill']['VendorAddress_Addr5']);
$this->setVendorAddress_City($_SESSION['bill']['VendorAddress_City']);
$this->setVendorAddress_State($_SESSION['bill']['VendorAddress_State']);
$this->setVendorAddress_PostalCode($_SESSION['bill']['VendorAddress_PostalCode']);
$this->setVendorAddress_Country($_SESSION['bill']['VendorAddress_Country']);
$this->setVendorAddress_Note($_SESSION['bill']['VendorAddress_Note']);
$this->setAPAccountRef_ListID($_SESSION['bill']['APAccountRef_ListID']);
$this->setAPAccountRef_FullName($_SESSION['bill']['APAccountRef_FullName']);
$this->setTxnDate($_SESSION['bill']['TxnDate']);
$this->setDueDate($_SESSION['bill']['DueDate']);
$this->setAmountDue($_SESSION['bill']['AmountDue']);
$this->setCurrencyRef_ListID($_SESSION['bill']['CurrencyRef_ListID']);
$this->setCurrencyRef_FullName($_SESSION['bill']['CurrencyRef_FullName']);
$this->setExchangeRate($_SESSION['bill']['ExchangeRate']);
$this->setAmountDueInHomeCurrency($_SESSION['bill']['AmountDueInHomeCurrency']);
$this->setRefNumber($_SESSION['bill']['RefNumber']);
$this->setTermsRef_ListID($_SESSION['bill']['TermsRef_ListID']);
$this->setTermsRef_FullName($_SESSION['bill']['TermsRef_FullName']);
$this->setMemo($_SESSION['bill']['Memo']);
$this->setIsTaxIncluded($_SESSION['bill']['IsTaxIncluded']);
$this->setSalesTaxCodeRef_ListID($_SESSION['bill']['SalesTaxCodeRef_ListID']);
$this->setSalesTaxCodeRef_FullName($_SESSION['bill']['SalesTaxCodeRef_FullName']);
$this->setIsPaID($_SESSION['bill']['IsPaID']);
$this->setOpenAmount($_SESSION['bill']['OpenAmount']);
$this->setCustomField1($_SESSION['bill']['CustomField1']);
$this->setCustomField2($_SESSION['bill']['CustomField2']);
$this->setCustomField3($_SESSION['bill']['CustomField3']);
$this->setCustomField4($_SESSION['bill']['CustomField4']);
$this->setCustomField5($_SESSION['bill']['CustomField5']);
$this->setCustomField6($_SESSION['bill']['CustomField6']);
$this->setCustomField7($_SESSION['bill']['CustomField7']);
$this->setCustomField8($_SESSION['bill']['CustomField8']);
$this->setCustomField9($_SESSION['bill']['CustomField9']);
$this->setCustomField10($_SESSION['bill']['CustomField10']);
$this->setCustomField11($_SESSION['bill']['CustomField11']);
$this->setCustomField12($_SESSION['bill']['CustomField12']);
$this->setCustomField13($_SESSION['bill']['CustomField13']);
$this->setCustomField14($_SESSION['bill']['CustomField14']);
$this->setCustomField15($_SESSION['bill']['CustomField15']);
$this->setStatus($_SESSION['bill']['Status']);

}

function genLimpia_bill()
{
$_SESSION['bill']['TxnID'] = ' ';
$_SESSION['bill']['TimeCreated'] = ' ';
$_SESSION['bill']['TimeModified'] = ' ';
$_SESSION['bill']['EditSequence'] = ' ';
$_SESSION['bill']['TxnNumber'] = ' ';
$_SESSION['bill']['VendorRef_ListID'] = ' ';
$_SESSION['bill']['VendorRef_FullName'] = ' ';
$_SESSION['bill']['VendorAddress_Addr1'] = ' ';
$_SESSION['bill']['VendorAddress_Addr2'] = ' ';
$_SESSION['bill']['VendorAddress_Addr3'] = ' ';
$_SESSION['bill']['VendorAddress_Addr4'] = ' ';
$_SESSION['bill']['VendorAddress_Addr5'] = ' ';
$_SESSION['bill']['VendorAddress_City'] = ' ';
$_SESSION['bill']['VendorAddress_State'] = ' ';
$_SESSION['bill']['VendorAddress_PostalCode'] = ' ';
$_SESSION['bill']['VendorAddress_Country'] = ' ';
$_SESSION['bill']['VendorAddress_Note'] = ' ';
$_SESSION['bill']['APAccountRef_ListID'] = ' ';
$_SESSION['bill']['APAccountRef_FullName'] = ' ';
$_SESSION['bill']['TxnDate'] = ' ';
$_SESSION['bill']['DueDate'] = ' ';
$_SESSION['bill']['AmountDue'] = ' ';
$_SESSION['bill']['CurrencyRef_ListID'] = ' ';
$_SESSION['bill']['CurrencyRef_FullName'] = ' ';
$_SESSION['bill']['ExchangeRate'] = ' ';
$_SESSION['bill']['AmountDueInHomeCurrency'] = ' ';
$_SESSION['bill']['RefNumber'] = ' ';
$_SESSION['bill']['TermsRef_ListID'] = ' ';
$_SESSION['bill']['TermsRef_FullName'] = ' ';
$_SESSION['bill']['Memo'] = ' ';
$_SESSION['bill']['IsTaxIncluded'] = ' ';
$_SESSION['bill']['SalesTaxCodeRef_ListID'] = ' ';
$_SESSION['bill']['SalesTaxCodeRef_FullName'] = ' ';
$_SESSION['bill']['IsPaID'] = ' ';
$_SESSION['bill']['OpenAmount'] = ' ';
$_SESSION['bill']['CustomField1'] = ' ';
$_SESSION['bill']['CustomField2'] = ' ';
$_SESSION['bill']['CustomField3'] = ' ';
$_SESSION['bill']['CustomField4'] = ' ';
$_SESSION['bill']['CustomField5'] = ' ';
$_SESSION['bill']['CustomField6'] = ' ';
$_SESSION['bill']['CustomField7'] = ' ';
$_SESSION['bill']['CustomField8'] = ' ';
$_SESSION['bill']['CustomField9'] = ' ';
$_SESSION['bill']['CustomField10'] = ' ';
$_SESSION['bill']['CustomField11'] = ' ';
$_SESSION['bill']['CustomField12'] = ' ';
$_SESSION['bill']['CustomField13'] = ' ';
$_SESSION['bill']['CustomField14'] = ' ';
$_SESSION['bill']['CustomField15'] = ' ';
$_SESSION['bill']['Status'] = ' ';

}

function gentraverse_bill($node)
{
$node->getElementsByTagName('TxnID')->item(0) == NULL ? $_SESSION['bill']['TxnID'] = ' ' : $_SESSION['bill']['TxnID'] = $node->getElementsByTagName('TxnID')->item(0)->nodeValue;
$node->getElementsByTagName('TimeCreated')->item(0) == NULL ? $_SESSION['bill']['TimeCreated'] = '2010-08-10' : $_SESSION['bill']['TimeCreated'] = $node->getElementsByTagName('TimeCreated')->item(0)->nodeValue;
$node->getElementsByTagName('TimeModified')->item(0) == NULL ? $_SESSION['bill']['TimeModified'] = '2010-08-10' : $_SESSION['bill']['TimeModified'] = $node->getElementsByTagName('TimeModified')->item(0)->nodeValue;
$node->getElementsByTagName('EditSequence')->item(0) == NULL ? $_SESSION['bill']['EditSequence'] = '2010-08-10' : $_SESSION['bill']['EditSequence'] = $node->getElementsByTagName('EditSequence')->item(0)->nodeValue;
$node->getElementsByTagName('TxnNumber')->item(0) == NULL ? $_SESSION['bill']['TxnNumber'] = '2010-08-10' : $_SESSION['bill']['TxnNumber'] = $node->getElementsByTagName('TxnNumber')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(0) == NULL ? $_SESSION['bill']['VendorRef_ListID'] = ' ' : $_SESSION['bill']['VendorRef_ListID'] = $node->getElementsByTagName('ListID')->item(0)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['bill']['VendorRef_FullName'] = ' ' : $_SESSION['bill']['VendorRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('Addr1')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_Addr1'] = ' ' : $_SESSION['bill']['VendorAddress_Addr1'] = $node->getElementsByTagName('Addr1')->item(0)->nodeValue;
$node->getElementsByTagName('Addr2')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_Addr2'] = ' ' : $_SESSION['bill']['VendorAddress_Addr2'] = $node->getElementsByTagName('Addr2')->item(0)->nodeValue;
$node->getElementsByTagName('Addr3')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_Addr3'] = ' ' : $_SESSION['bill']['VendorAddress_Addr3'] = $node->getElementsByTagName('Addr3')->item(0)->nodeValue;
$node->getElementsByTagName('Addr4')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_Addr4'] = ' ' : $_SESSION['bill']['VendorAddress_Addr4'] = $node->getElementsByTagName('Addr4')->item(0)->nodeValue;
$node->getElementsByTagName('Addr5')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_Addr5'] = ' ' : $_SESSION['bill']['VendorAddress_Addr5'] = $node->getElementsByTagName('Addr5')->item(0)->nodeValue;
$node->getElementsByTagName('City')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_City'] = ' ' : $_SESSION['bill']['VendorAddress_City'] = $node->getElementsByTagName('City')->item(0)->nodeValue;
$node->getElementsByTagName('State')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_State'] = ' ' : $_SESSION['bill']['VendorAddress_State'] = $node->getElementsByTagName('State')->item(0)->nodeValue;
$node->getElementsByTagName('PostalCode')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_PostalCode'] = ' ' : $_SESSION['bill']['VendorAddress_PostalCode'] = $node->getElementsByTagName('PostalCode')->item(0)->nodeValue;
$node->getElementsByTagName('Country')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_Country'] = ' ' : $_SESSION['bill']['VendorAddress_Country'] = $node->getElementsByTagName('Country')->item(0)->nodeValue;
$node->getElementsByTagName('Note')->item(0) == NULL ? $_SESSION['bill']['VendorAddress_Note'] = ' ' : $_SESSION['bill']['VendorAddress_Note'] = $node->getElementsByTagName('Note')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(0) == NULL ? $_SESSION['bill']['APAccountRef_ListID'] = ' ' : $_SESSION['bill']['APAccountRef_ListID'] = $node->getElementsByTagName('ListID')->item(0)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['bill']['APAccountRef_FullName'] = ' ' : $_SESSION['bill']['APAccountRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('TxnDate')->item(0) == NULL ? $_SESSION['bill']['TxnDate'] = '2010-08-10' : $_SESSION['bill']['TxnDate'] = $node->getElementsByTagName('TxnDate')->item(0)->nodeValue;
$node->getElementsByTagName('DueDate')->item(0) == NULL ? $_SESSION['bill']['DueDate'] = '2010-08-10' : $_SESSION['bill']['DueDate'] = $node->getElementsByTagName('DueDate')->item(0)->nodeValue;
$node->getElementsByTagName('AmountDue')->item(0) == NULL ? $_SESSION['bill']['AmountDue'] = 0 : $_SESSION['bill']['AmountDue'] = $node->getElementsByTagName('AmountDue')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(0) == NULL ? $_SESSION['bill']['CurrencyRef_ListID'] = ' ' : $_SESSION['bill']['CurrencyRef_ListID'] = $node->getElementsByTagName('ListID')->item(0)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['bill']['CurrencyRef_FullName'] = ' ' : $_SESSION['bill']['CurrencyRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('ExchangeRate')->item(0) == NULL ? $_SESSION['bill']['ExchangeRate'] = 0 : $_SESSION['bill']['ExchangeRate'] = $node->getElementsByTagName('ExchangeRate')->item(0)->nodeValue;
$node->getElementsByTagName('AmountDueInHomeCurrency')->item(0) == NULL ? $_SESSION['bill']['AmountDueInHomeCurrency'] = 0 : $_SESSION['bill']['AmountDueInHomeCurrency'] = $node->getElementsByTagName('AmountDueInHomeCurrency')->item(0)->nodeValue;
$node->getElementsByTagName('RefNumber')->item(0) == NULL ? $_SESSION['bill']['RefNumber'] = ' ' : $_SESSION['bill']['RefNumber'] = $node->getElementsByTagName('RefNumber')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(0) == NULL ? $_SESSION['bill']['TermsRef_ListID'] = ' ' : $_SESSION['bill']['TermsRef_ListID'] = $node->getElementsByTagName('ListID')->item(0)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['bill']['TermsRef_FullName'] = ' ' : $_SESSION['bill']['TermsRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('Memo')->item(0) == NULL ? $_SESSION['bill']['Memo'] = ' ' : $_SESSION['bill']['Memo'] = $node->getElementsByTagName('Memo')->item(0)->nodeValue;
$node->getElementsByTagName('IsTaxIncluded')->item(0) == NULL ? $_SESSION['bill']['IsTaxIncluded'] = ' ' : $_SESSION['bill']['IsTaxIncluded'] = $node->getElementsByTagName('IsTaxIncluded')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(0) == NULL ? $_SESSION['bill']['SalesTaxCodeRef_ListID'] = ' ' : $_SESSION['bill']['SalesTaxCodeRef_ListID'] = $node->getElementsByTagName('ListID')->item(0)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['bill']['SalesTaxCodeRef_FullName'] = ' ' : $_SESSION['bill']['SalesTaxCodeRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('IsPaID')->item(0) == NULL ? $_SESSION['bill']['IsPaID'] = ' ' : $_SESSION['bill']['IsPaID'] = $node->getElementsByTagName('IsPaID')->item(0)->nodeValue;
$node->getElementsByTagName('OpenAmount')->item(0) == NULL ? $_SESSION['bill']['OpenAmount'] = 0 : $_SESSION['bill']['OpenAmount'] = $node->getElementsByTagName('OpenAmount')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField1')->item(0) == NULL ? $_SESSION['bill']['CustomField1'] = ' ' : $_SESSION['bill']['CustomField1'] = $node->getElementsByTagName('CustomField1')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField2')->item(0) == NULL ? $_SESSION['bill']['CustomField2'] = ' ' : $_SESSION['bill']['CustomField2'] = $node->getElementsByTagName('CustomField2')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField3')->item(0) == NULL ? $_SESSION['bill']['CustomField3'] = ' ' : $_SESSION['bill']['CustomField3'] = $node->getElementsByTagName('CustomField3')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField4')->item(0) == NULL ? $_SESSION['bill']['CustomField4'] = ' ' : $_SESSION['bill']['CustomField4'] = $node->getElementsByTagName('CustomField4')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField5')->item(0) == NULL ? $_SESSION['bill']['CustomField5'] = ' ' : $_SESSION['bill']['CustomField5'] = $node->getElementsByTagName('CustomField5')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField6')->item(0) == NULL ? $_SESSION['bill']['CustomField6'] = ' ' : $_SESSION['bill']['CustomField6'] = $node->getElementsByTagName('CustomField6')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField7')->item(0) == NULL ? $_SESSION['bill']['CustomField7'] = ' ' : $_SESSION['bill']['CustomField7'] = $node->getElementsByTagName('CustomField7')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField8')->item(0) == NULL ? $_SESSION['bill']['CustomField8'] = ' ' : $_SESSION['bill']['CustomField8'] = $node->getElementsByTagName('CustomField8')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField9')->item(0) == NULL ? $_SESSION['bill']['CustomField9'] = ' ' : $_SESSION['bill']['CustomField9'] = $node->getElementsByTagName('CustomField9')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField10')->item(0) == NULL ? $_SESSION['bill']['CustomField10'] = ' ' : $_SESSION['bill']['CustomField10'] = $node->getElementsByTagName('CustomField10')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField11')->item(0) == NULL ? $_SESSION['bill']['CustomField11'] = ' ' : $_SESSION['bill']['CustomField11'] = $node->getElementsByTagName('CustomField11')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField12')->item(0) == NULL ? $_SESSION['bill']['CustomField12'] = ' ' : $_SESSION['bill']['CustomField12'] = $node->getElementsByTagName('CustomField12')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField13')->item(0) == NULL ? $_SESSION['bill']['CustomField13'] = ' ' : $_SESSION['bill']['CustomField13'] = $node->getElementsByTagName('CustomField13')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField14')->item(0) == NULL ? $_SESSION['bill']['CustomField14'] = ' ' : $_SESSION['bill']['CustomField14'] = $node->getElementsByTagName('CustomField14')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField15')->item(0) == NULL ? $_SESSION['bill']['CustomField15'] = ' ' : $_SESSION['bill']['CustomField15'] = $node->getElementsByTagName('CustomField15')->item(0)->nodeValue;
$node->getElementsByTagName('Status')->item(0) == NULL ? $_SESSION['bill']['Status'] = ' ' : $_SESSION['bill']['Status'] = $node->getElementsByTagName('Status')->item(0)->nodeValue;

}

function adiciona_bill()
{
        $this->estado = 'ERR';
	$this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
        $sql = 'INSERT INTO bill (  TxnID, TimeCreated, TimeModified, EditSequence, TxnNumber, VendorRef_ListID, VendorRef_FullName, VendorAddress_Addr1, VendorAddress_Addr2, VendorAddress_Addr3, VendorAddress_Addr4, VendorAddress_Addr5, VendorAddress_City, VendorAddress_State, VendorAddress_PostalCode, VendorAddress_Country, VendorAddress_Note, APAccountRef_ListID, APAccountRef_FullName, TxnDate, DueDate, AmountDue, CurrencyRef_ListID, CurrencyRef_FullName, ExchangeRate, AmountDueInHomeCurrency, RefNumber, TermsRef_ListID, TermsRef_FullName, Memo, IsTaxIncluded, SalesTaxCodeRef_ListID, SalesTaxCodeRef_FullName, IsPaID, OpenAmount, CustomField1, CustomField2, CustomField3, CustomField4, CustomField5, CustomField6, CustomField7, CustomField8, CustomField9, CustomField10, CustomField11, CustomField12, CustomField13, CustomField14, CustomField15, Status) VALUES ( :TxnID, :TimeCreated, :TimeModified, :EditSequence, :TxnNumber, :VendorRef_ListID, :VendorRef_FullName, :VendorAddress_Addr1, :VendorAddress_Addr2, :VendorAddress_Addr3, :VendorAddress_Addr4, :VendorAddress_Addr5, :VendorAddress_City, :VendorAddress_State, :VendorAddress_PostalCode, :VendorAddress_Country, :VendorAddress_Note, :APAccountRef_ListID, :APAccountRef_FullName, :TxnDate, :DueDate, :AmountDue, :CurrencyRef_ListID, :CurrencyRef_FullName, :ExchangeRate, :AmountDueInHomeCurrency, :RefNumber, :TermsRef_ListID, :TermsRef_FullName, :Memo, :IsTaxIncluded, :SalesTaxCodeRef_ListID, :SalesTaxCodeRef_FullName, :IsPaID, :OpenAmount, :CustomField1, :CustomField2, :CustomField3, :CustomField4, :CustomField5, :CustomField6, :CustomField7, :CustomField8, :CustomField9, :CustomField10, :CustomField11, :CustomField12, :CustomField13, :CustomField14, :CustomField15, :Status)';
	$stmt = $this->db->prepare($sql);
	 $stmt->bindParam(':TxnID', $_SESSION['bill']['TxnID'] );
	$stmt->bindParam(':TimeCreated', $_SESSION['bill']['TimeCreated'] );
	$stmt->bindParam(':TimeModified', $_SESSION['bill']['TimeModified'] );
	$stmt->bindParam(':EditSequence', $_SESSION['bill']['EditSequence'] );
	$stmt->bindParam(':TxnNumber', $_SESSION['bill']['TxnNumber'] );
	$stmt->bindParam(':VendorRef_ListID', $_SESSION['bill']['VendorRef_ListID'] );
	$stmt->bindParam(':VendorRef_FullName', $_SESSION['bill']['VendorRef_FullName'] );
	$stmt->bindParam(':VendorAddress_Addr1', $_SESSION['bill']['VendorAddress_Addr1'] );
	$stmt->bindParam(':VendorAddress_Addr2', $_SESSION['bill']['VendorAddress_Addr2'] );
	$stmt->bindParam(':VendorAddress_Addr3', $_SESSION['bill']['VendorAddress_Addr3'] );
	$stmt->bindParam(':VendorAddress_Addr4', $_SESSION['bill']['VendorAddress_Addr4'] );
	$stmt->bindParam(':VendorAddress_Addr5', $_SESSION['bill']['VendorAddress_Addr5'] );
	$stmt->bindParam(':VendorAddress_City', $_SESSION['bill']['VendorAddress_City'] );
	$stmt->bindParam(':VendorAddress_State', $_SESSION['bill']['VendorAddress_State'] );
	$stmt->bindParam(':VendorAddress_PostalCode', $_SESSION['bill']['VendorAddress_PostalCode'] );
	$stmt->bindParam(':VendorAddress_Country', $_SESSION['bill']['VendorAddress_Country'] );
	$stmt->bindParam(':VendorAddress_Note', $_SESSION['bill']['VendorAddress_Note'] );
	$stmt->bindParam(':APAccountRef_ListID', $_SESSION['bill']['APAccountRef_ListID'] );
	$stmt->bindParam(':APAccountRef_FullName', $_SESSION['bill']['APAccountRef_FullName'] );
	$stmt->bindParam(':TxnDate', $_SESSION['bill']['TxnDate'] );
	$stmt->bindParam(':DueDate', $_SESSION['bill']['DueDate'] );
	$stmt->bindParam(':AmountDue', $_SESSION['bill']['AmountDue'] );
	$stmt->bindParam(':CurrencyRef_ListID', $_SESSION['bill']['CurrencyRef_ListID'] );
	$stmt->bindParam(':CurrencyRef_FullName', $_SESSION['bill']['CurrencyRef_FullName'] );
	$stmt->bindParam(':ExchangeRate', $_SESSION['bill']['ExchangeRate'] );
	$stmt->bindParam(':AmountDueInHomeCurrency', $_SESSION['bill']['AmountDueInHomeCurrency'] );
	$stmt->bindParam(':RefNumber', $_SESSION['bill']['RefNumber'] );
	$stmt->bindParam(':TermsRef_ListID', $_SESSION['bill']['TermsRef_ListID'] );
	$stmt->bindParam(':TermsRef_FullName', $_SESSION['bill']['TermsRef_FullName'] );
	$stmt->bindParam(':Memo', $_SESSION['bill']['Memo'] );
	$stmt->bindParam(':IsTaxIncluded', $_SESSION['bill']['IsTaxIncluded'] );
	$stmt->bindParam(':SalesTaxCodeRef_ListID', $_SESSION['bill']['SalesTaxCodeRef_ListID'] );
	$stmt->bindParam(':SalesTaxCodeRef_FullName', $_SESSION['bill']['SalesTaxCodeRef_FullName'] );
	$stmt->bindParam(':IsPaID', $_SESSION['bill']['IsPaID'] );
	$stmt->bindParam(':OpenAmount', $_SESSION['bill']['OpenAmount'] );
	$stmt->bindParam(':CustomField1', $_SESSION['bill']['CustomField1'] );
	$stmt->bindParam(':CustomField2', $_SESSION['bill']['CustomField2'] );
	$stmt->bindParam(':CustomField3', $_SESSION['bill']['CustomField3'] );
	$stmt->bindParam(':CustomField4', $_SESSION['bill']['CustomField4'] );
	$stmt->bindParam(':CustomField5', $_SESSION['bill']['CustomField5'] );
	$stmt->bindParam(':CustomField6', $_SESSION['bill']['CustomField6'] );
	$stmt->bindParam(':CustomField7', $_SESSION['bill']['CustomField7'] );
	$stmt->bindParam(':CustomField8', $_SESSION['bill']['CustomField8'] );
	$stmt->bindParam(':CustomField9', $_SESSION['bill']['CustomField9'] );
	$stmt->bindParam(':CustomField10', $_SESSION['bill']['CustomField10'] );
	$stmt->bindParam(':CustomField11', $_SESSION['bill']['CustomField11'] );
	$stmt->bindParam(':CustomField12', $_SESSION['bill']['CustomField12'] );
	$stmt->bindParam(':CustomField13', $_SESSION['bill']['CustomField13'] );
	$stmt->bindParam(':CustomField14', $_SESSION['bill']['CustomField14'] );
	$stmt->bindParam(':CustomField15', $_SESSION['bill']['CustomField15'] );
	$stmt->bindParam(':Status', $_SESSION['bill']['Status'] );
	$stmt->execute();
        } catch(PDOException $e) {
            echo $e->getMessage();
        }    
}

function quitaslashes_bill()
{
         $_SESSION['bill']['TxnID'] = htmlspecialchars(strip_tags($_SESSION['bill']['TxnID']));
$_SESSION['bill']['TimeCreated'] = htmlspecialchars(strip_tags($_SESSION['bill']['TimeCreated']));
$_SESSION['bill']['TimeModified'] = htmlspecialchars(strip_tags($_SESSION['bill']['TimeModified']));
$_SESSION['bill']['EditSequence'] = htmlspecialchars(strip_tags($_SESSION['bill']['EditSequence']));
$_SESSION['bill']['TxnNumber'] = htmlspecialchars(strip_tags($_SESSION['bill']['TxnNumber']));
$_SESSION['bill']['VendorRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorRef_ListID']));
$_SESSION['bill']['VendorRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorRef_FullName']));
$_SESSION['bill']['VendorAddress_Addr1'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_Addr1']));
$_SESSION['bill']['VendorAddress_Addr2'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_Addr2']));
$_SESSION['bill']['VendorAddress_Addr3'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_Addr3']));
$_SESSION['bill']['VendorAddress_Addr4'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_Addr4']));
$_SESSION['bill']['VendorAddress_Addr5'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_Addr5']));
$_SESSION['bill']['VendorAddress_City'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_City']));
$_SESSION['bill']['VendorAddress_State'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_State']));
$_SESSION['bill']['VendorAddress_PostalCode'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_PostalCode']));
$_SESSION['bill']['VendorAddress_Country'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_Country']));
$_SESSION['bill']['VendorAddress_Note'] = htmlspecialchars(strip_tags($_SESSION['bill']['VendorAddress_Note']));
$_SESSION['bill']['APAccountRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['bill']['APAccountRef_ListID']));
$_SESSION['bill']['APAccountRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['bill']['APAccountRef_FullName']));
$_SESSION['bill']['TxnDate'] = htmlspecialchars(strip_tags($_SESSION['bill']['TxnDate']));
$_SESSION['bill']['DueDate'] = htmlspecialchars(strip_tags($_SESSION['bill']['DueDate']));
$_SESSION['bill']['AmountDue'] = htmlspecialchars(strip_tags($_SESSION['bill']['AmountDue']));
$_SESSION['bill']['CurrencyRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['bill']['CurrencyRef_ListID']));
$_SESSION['bill']['CurrencyRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['bill']['CurrencyRef_FullName']));
$_SESSION['bill']['ExchangeRate'] = htmlspecialchars(strip_tags($_SESSION['bill']['ExchangeRate']));
$_SESSION['bill']['AmountDueInHomeCurrency'] = htmlspecialchars(strip_tags($_SESSION['bill']['AmountDueInHomeCurrency']));
$_SESSION['bill']['RefNumber'] = htmlspecialchars(strip_tags($_SESSION['bill']['RefNumber']));
$_SESSION['bill']['TermsRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['bill']['TermsRef_ListID']));
$_SESSION['bill']['TermsRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['bill']['TermsRef_FullName']));
$_SESSION['bill']['Memo'] = htmlspecialchars(strip_tags($_SESSION['bill']['Memo']));
$_SESSION['bill']['IsTaxIncluded'] = htmlspecialchars(strip_tags($_SESSION['bill']['IsTaxIncluded']));
$_SESSION['bill']['SalesTaxCodeRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['bill']['SalesTaxCodeRef_ListID']));
$_SESSION['bill']['SalesTaxCodeRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['bill']['SalesTaxCodeRef_FullName']));
$_SESSION['bill']['IsPaID'] = htmlspecialchars(strip_tags($_SESSION['bill']['IsPaID']));
$_SESSION['bill']['OpenAmount'] = htmlspecialchars(strip_tags($_SESSION['bill']['OpenAmount']));
$_SESSION['bill']['CustomField1'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField1']));
$_SESSION['bill']['CustomField2'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField2']));
$_SESSION['bill']['CustomField3'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField3']));
$_SESSION['bill']['CustomField4'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField4']));
$_SESSION['bill']['CustomField5'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField5']));
$_SESSION['bill']['CustomField6'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField6']));
$_SESSION['bill']['CustomField7'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField7']));
$_SESSION['bill']['CustomField8'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField8']));
$_SESSION['bill']['CustomField9'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField9']));
$_SESSION['bill']['CustomField10'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField10']));
$_SESSION['bill']['CustomField11'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField11']));
$_SESSION['bill']['CustomField12'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField12']));
$_SESSION['bill']['CustomField13'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField13']));
$_SESSION['bill']['CustomField14'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField14']));
$_SESSION['bill']['CustomField15'] = htmlspecialchars(strip_tags($_SESSION['bill']['CustomField15']));
$_SESSION['bill']['Status'] = htmlspecialchars(strip_tags($_SESSION['bill']['Status']));

 
    }
    


// **********************
// GETTER METHODS
// **********************


function getTxnID()
{
return $this->TxnID;
}

function getTimeCreated()
{
return $this->TimeCreated;
}

function getTimeModified()
{
return $this->TimeModified;
}

function getEditSequence()
{
return $this->EditSequence;
}

function getTxnNumber()
{
return $this->TxnNumber;
}

function getVendorRef_ListID()
{
return $this->VendorRef_ListID;
}

function getVendorRef_FullName()
{
return $this->VendorRef_FullName;
}

function getVendorAddress_Addr1()
{
return $this->VendorAddress_Addr1;
}

function getVendorAddress_Addr2()
{
return $this->VendorAddress_Addr2;
}

function getVendorAddress_Addr3()
{
return $this->VendorAddress_Addr3;
}

function getVendorAddress_Addr4()
{
return $this->VendorAddress_Addr4;
}

function getVendorAddress_Addr5()
{
return $this->VendorAddress_Addr5;
}

function getVendorAddress_City()
{
return $this->VendorAddress_City;
}

function getVendorAddress_State()
{
return $this->VendorAddress_State;
}

function getVendorAddress_PostalCode()
{
return $this->VendorAddress_PostalCode;
}

function getVendorAddress_Country()
{
return $this->VendorAddress_Country;
}

function getVendorAddress_Note()
{
return $this->VendorAddress_Note;
}

function getAPAccountRef_ListID()
{
return $this->APAccountRef_ListID;
}

function getAPAccountRef_FullName()
{
return $this->APAccountRef_FullName;
}

function getTxnDate()
{
return $this->TxnDate;
}

function getDueDate()
{
return $this->DueDate;
}

function getAmountDue()
{
return $this->AmountDue;
}

function getCurrencyRef_ListID()
{
return $this->CurrencyRef_ListID;
}

function getCurrencyRef_FullName()
{
return $this->CurrencyRef_FullName;
}

function getExchangeRate()
{
return $this->ExchangeRate;
}

function getAmountDueInHomeCurrency()
{
return $this->AmountDueInHomeCurrency;
}

function getRefNumber()
{
return $this->RefNumber;
}

function getTermsRef_ListID()
{
return $this->TermsRef_ListID;
}

function getTermsRef_FullName()
{
return $this->TermsRef_FullName;
}

function getMemo()
{
return $this->Memo;
}

function getIsTaxIncluded()
{
return $this->IsTaxIncluded;
}

function getSalesTaxCodeRef_ListID()
{
return $this->SalesTaxCodeRef_ListID;
}

function getSalesTaxCodeRef_FullName()
{
return $this->SalesTaxCodeRef_FullName;
}

function getIsPaID()
{
return $this->IsPaID;
}

function getOpenAmount()
{
return $this->OpenAmount;
}

function getCustomField1()
{
return $this->CustomField1;
}

function getCustomField2()
{
return $this->CustomField2;
}

function getCustomField3()
{
return $this->CustomField3;
}

function getCustomField4()
{
return $this->CustomField4;
}

function getCustomField5()
{
return $this->CustomField5;
}

function getCustomField6()
{
return $this->CustomField6;
}

function getCustomField7()
{
return $this->CustomField7;
}

function getCustomField8()
{
return $this->CustomField8;
}

function getCustomField9()
{
return $this->CustomField9;
}

function getCustomField10()
{
return $this->CustomField10;
}

function getCustomField11()
{
return $this->CustomField11;
}

function getCustomField12()
{
return $this->CustomField12;
}

function getCustomField13()
{
return $this->CustomField13;
}

function getCustomField14()
{
return $this->CustomField14;
}

function getCustomField15()
{
return $this->CustomField15;
}

function getStatus()
{
return $this->Status;
}

// **********************
// SETTER METHODS
// **********************


function setTxnID($val)
{
$this->TxnID =  $val;
}

function setTimeCreated($val)
{
$this->TimeCreated =  $val;
}

function setTimeModified($val)
{
$this->TimeModified =  $val;
}

function setEditSequence($val)
{
$this->EditSequence =  $val;
}

function setTxnNumber($val)
{
$this->TxnNumber =  $val;
}

function setVendorRef_ListID($val)
{
$this->VendorRef_ListID =  $val;
}

function setVendorRef_FullName($val)
{
$this->VendorRef_FullName =  $val;
}

function setVendorAddress_Addr1($val)
{
$this->VendorAddress_Addr1 =  $val;
}

function setVendorAddress_Addr2($val)
{
$this->VendorAddress_Addr2 =  $val;
}

function setVendorAddress_Addr3($val)
{
$this->VendorAddress_Addr3 =  $val;
}

function setVendorAddress_Addr4($val)
{
$this->VendorAddress_Addr4 =  $val;
}

function setVendorAddress_Addr5($val)
{
$this->VendorAddress_Addr5 =  $val;
}

function setVendorAddress_City($val)
{
$this->VendorAddress_City =  $val;
}

function setVendorAddress_State($val)
{
$this->VendorAddress_State =  $val;
}

function setVendorAddress_PostalCode($val)
{
$this->VendorAddress_PostalCode =  $val;
}

function setVendorAddress_Country($val)
{
$this->VendorAddress_Country =  $val;
}

function setVendorAddress_Note($val)
{
$this->VendorAddress_Note =  $val;
}

function setAPAccountRef_ListID($val)
{
$this->APAccountRef_ListID =  $val;
}

function setAPAccountRef_FullName($val)
{
$this->APAccountRef_FullName =  $val;
}

function setTxnDate($val)
{
$this->TxnDate =  $val;
}

function setDueDate($val)
{
$this->DueDate =  $val;
}

function setAmountDue($val)
{
$this->AmountDue =  $val;
}

function setCurrencyRef_ListID($val)
{
$this->CurrencyRef_ListID =  $val;
}

function setCurrencyRef_FullName($val)
{
$this->CurrencyRef_FullName =  $val;
}

function setExchangeRate($val)
{
$this->ExchangeRate =  $val;
}

function setAmountDueInHomeCurrency($val)
{
$this->AmountDueInHomeCurrency =  $val;
}

function setRefNumber($val)
{
$this->RefNumber =  $val;
}

function setTermsRef_ListID($val)
{
$this->TermsRef_ListID =  $val;
}

function setTermsRef_FullName($val)
{
$this->TermsRef_FullName =  $val;
}

function setMemo($val)
{
$this->Memo =  $val;
}

function setIsTaxIncluded($val)
{
$this->IsTaxIncluded =  $val;
}

function setSalesTaxCodeRef_ListID($val)
{
$this->SalesTaxCodeRef_ListID =  $val;
}

function setSalesTaxCodeRef_FullName($val)
{
$this->SalesTaxCodeRef_FullName =  $val;
}

function setIsPaID($val)
{
$this->IsPaID =  $val;
}

function setOpenAmount($val)
{
$this->OpenAmount =  $val;
}

function setCustomField1($val)
{
$this->CustomField1 =  $val;
}

function setCustomField2($val)
{
$this->CustomField2 =  $val;
}

function setCustomField3($val)
{
$this->CustomField3 =  $val;
}

function setCustomField4($val)
{
$this->CustomField4 =  $val;
}

function setCustomField5($val)
{
$this->CustomField5 =  $val;
}

function setCustomField6($val)
{
$this->CustomField6 =  $val;
}

function setCustomField7($val)
{
$this->CustomField7 =  $val;
}

function setCustomField8($val)
{
$this->CustomField8 =  $val;
}

function setCustomField9($val)
{
$this->CustomField9 =  $val;
}

function setCustomField10($val)
{
$this->CustomField10 =  $val;
}

function setCustomField11($val)
{
$this->CustomField11 =  $val;
}

function setCustomField12($val)
{
$this->CustomField12 =  $val;
}

function setCustomField13($val)
{
$this->CustomField13 =  $val;
}

function setCustomField14($val)
{
$this->CustomField14 =  $val;
}

function setCustomField15($val)
{
$this->CustomField15 =  $val;
}

function setStatus($val)
{
$this->Status =  $val;
}

// ************************************************************************************
// SELECT busca igual en el campo estado retorna OK si existe el registro
//          retorna actualiza si es el mismo registro y tambien carga en la instancia
//          los valores de la lectura
// *************************************************************************************

    function buscaIgual_bill() {
        $estado = 'ERR';
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
            $sql =  'SELECT * FROM invoice WHERE TxnID = :clave ';
            $stmt = $this->db->prepare($sql);
            $stmt->bindParam(':clave', $_SESSION['bill']['TxnID']);
            $stmt->execute();
            $registro = $stmt->fetch(PDO::FETCH_ASSOC);
            if ( ! $registro){
                $this->estado = 'OK';
            } else {
                if ($registro['TxnID'] === $_SESSION['bill']['TxnID']) {
                $this->estado = 'ACTUALIZA';
                }
            }
            
        } catch(PDOException $e) {
            echo $e->getMessage();
        } 
    
    return $this->estado;
    }
// ************************************************************************************
// SELECT dependiendo de las condiones recibidas desde el programa llamado se parsea
//          el archivo json para cargar las comparaciones y tambien los nombres de las variables
//          para una lectura de todos los registros que cumplan la condicion
// *************************************************************************************

    function leetodos_bill() {
        $estado = 'ERR';
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
            $sql =  'SELECT * FROM invoice WHERE TxnID = :clave ';
            $stmt = $this->db->prepare($sql);
            $stmt->bindParam(':clave', $_SESSION['bill']['TxnID']);
            $stmt->execute();
            $registro = $stmt->fetchAll(PDO::FETCH_ASSOC);
            if ( ! $registro){
                $this->estado = 'OK';
            } else {
                $this->estado = 'TODOS';
            }
            
        } catch(PDOException $e) {
            echo $e->getMessage();
        } 
    
    return $this->estado;
    }
// **********************
// SELECT METHOD / LOAD
// **********************

function select_bill()
{

$this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	try {
$sql = 'SELECT * FROM bill WHERE TxnID = :clave'; 
$stmt = $this->db->prepare($sql);
    $stmt->bindParam(":clave", $_SESSION['bill']['TxnID']);
        $stmt->execute();
	$registro = $stmt->fetch(PDO::FETCH_ASSOC);
	if ( ! $registro) {
		$this->estado = 'OK';
		return $this->estado;
	} else {
                
		if ($registro['TxnID'] === $_SESSION['invoice']['TxnID']) {
                    $this->estado = 'ACTUALIZA';
                    }
                    }
            
                } catch(PDOException $e) {
                    echo $e->getMessage();
                }
                
		$this->TxnID = $registro['TxnID'];

		$this->TimeCreated = $registro['TimeCreated'];

		$this->TimeModified = $registro['TimeModified'];

		$this->EditSequence = $registro['EditSequence'];

		$this->TxnNumber = $registro['TxnNumber'];

		$this->VendorRef_ListID = $registro['VendorRef_ListID'];

		$this->VendorRef_FullName = $registro['VendorRef_FullName'];

		$this->VendorAddress_Addr1 = $registro['VendorAddress_Addr1'];

		$this->VendorAddress_Addr2 = $registro['VendorAddress_Addr2'];

		$this->VendorAddress_Addr3 = $registro['VendorAddress_Addr3'];

		$this->VendorAddress_Addr4 = $registro['VendorAddress_Addr4'];

		$this->VendorAddress_Addr5 = $registro['VendorAddress_Addr5'];

		$this->VendorAddress_City = $registro['VendorAddress_City'];

		$this->VendorAddress_State = $registro['VendorAddress_State'];

		$this->VendorAddress_PostalCode = $registro['VendorAddress_PostalCode'];

		$this->VendorAddress_Country = $registro['VendorAddress_Country'];

		$this->VendorAddress_Note = $registro['VendorAddress_Note'];

		$this->APAccountRef_ListID = $registro['APAccountRef_ListID'];

		$this->APAccountRef_FullName = $registro['APAccountRef_FullName'];

		$this->TxnDate = $registro['TxnDate'];

		$this->DueDate = $registro['DueDate'];

		$this->AmountDue = $registro['AmountDue'];

		$this->CurrencyRef_ListID = $registro['CurrencyRef_ListID'];

		$this->CurrencyRef_FullName = $registro['CurrencyRef_FullName'];

		$this->ExchangeRate = $registro['ExchangeRate'];

		$this->AmountDueInHomeCurrency = $registro['AmountDueInHomeCurrency'];

		$this->RefNumber = $registro['RefNumber'];

		$this->TermsRef_ListID = $registro['TermsRef_ListID'];

		$this->TermsRef_FullName = $registro['TermsRef_FullName'];

		$this->Memo = $registro['Memo'];

		$this->IsTaxIncluded = $registro['IsTaxIncluded'];

		$this->SalesTaxCodeRef_ListID = $registro['SalesTaxCodeRef_ListID'];

		$this->SalesTaxCodeRef_FullName = $registro['SalesTaxCodeRef_FullName'];

		$this->IsPaID = $registro['IsPaID'];

		$this->OpenAmount = $registro['OpenAmount'];

		$this->CustomField1 = $registro['CustomField1'];

		$this->CustomField2 = $registro['CustomField2'];

		$this->CustomField3 = $registro['CustomField3'];

		$this->CustomField4 = $registro['CustomField4'];

		$this->CustomField5 = $registro['CustomField5'];

		$this->CustomField6 = $registro['CustomField6'];

		$this->CustomField7 = $registro['CustomField7'];

		$this->CustomField8 = $registro['CustomField8'];

		$this->CustomField9 = $registro['CustomField9'];

		$this->CustomField10 = $registro['CustomField10'];

		$this->CustomField11 = $registro['CustomField11'];

		$this->CustomField12 = $registro['CustomField12'];

		$this->CustomField13 = $registro['CustomField13'];

		$this->CustomField14 = $registro['CustomField14'];

		$this->CustomField15 = $registro['CustomField15'];

		$this->Status = $registro['Status'];


}

// *******************************
// UNSET METHOD / clean
// *******************************

function cleanSession_bill()
{

                unset($_SESSION['bill']['TxnID']);
unset($_SESSION['bill']['TimeCreated']);
unset($_SESSION['bill']['TimeModified']);
unset($_SESSION['bill']['EditSequence']);
unset($_SESSION['bill']['TxnNumber']);
unset($_SESSION['bill']['VendorRef_ListID']);
unset($_SESSION['bill']['VendorRef_FullName']);
unset($_SESSION['bill']['VendorAddress_Addr1']);
unset($_SESSION['bill']['VendorAddress_Addr2']);
unset($_SESSION['bill']['VendorAddress_Addr3']);
unset($_SESSION['bill']['VendorAddress_Addr4']);
unset($_SESSION['bill']['VendorAddress_Addr5']);
unset($_SESSION['bill']['VendorAddress_City']);
unset($_SESSION['bill']['VendorAddress_State']);
unset($_SESSION['bill']['VendorAddress_PostalCode']);
unset($_SESSION['bill']['VendorAddress_Country']);
unset($_SESSION['bill']['VendorAddress_Note']);
unset($_SESSION['bill']['APAccountRef_ListID']);
unset($_SESSION['bill']['APAccountRef_FullName']);
unset($_SESSION['bill']['TxnDate']);
unset($_SESSION['bill']['DueDate']);
unset($_SESSION['bill']['AmountDue']);
unset($_SESSION['bill']['CurrencyRef_ListID']);
unset($_SESSION['bill']['CurrencyRef_FullName']);
unset($_SESSION['bill']['ExchangeRate']);
unset($_SESSION['bill']['AmountDueInHomeCurrency']);
unset($_SESSION['bill']['RefNumber']);
unset($_SESSION['bill']['TermsRef_ListID']);
unset($_SESSION['bill']['TermsRef_FullName']);
unset($_SESSION['bill']['Memo']);
unset($_SESSION['bill']['IsTaxIncluded']);
unset($_SESSION['bill']['SalesTaxCodeRef_ListID']);
unset($_SESSION['bill']['SalesTaxCodeRef_FullName']);
unset($_SESSION['bill']['IsPaID']);
unset($_SESSION['bill']['OpenAmount']);
unset($_SESSION['bill']['CustomField1']);
unset($_SESSION['bill']['CustomField2']);
unset($_SESSION['bill']['CustomField3']);
unset($_SESSION['bill']['CustomField4']);
unset($_SESSION['bill']['CustomField5']);
unset($_SESSION['bill']['CustomField6']);
unset($_SESSION['bill']['CustomField7']);
unset($_SESSION['bill']['CustomField8']);
unset($_SESSION['bill']['CustomField9']);
unset($_SESSION['bill']['CustomField10']);
unset($_SESSION['bill']['CustomField11']);
unset($_SESSION['bill']['CustomField12']);
unset($_SESSION['bill']['CustomField13']);
unset($_SESSION['bill']['CustomField14']);
unset($_SESSION['bill']['CustomField15']);
unset($_SESSION['bill']['Status']);


            }

// **********************
// DELETE
// **********************

function delete_bill($id)
{


}

// **********************
// UPDATE
// **********************

function update_bill()
{
    $this->estado = 'ERR';
	 $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            try {
	$sql = 'UPDATE bill SET TimeCreated=$this->TimeCreated,TimeModified=$this->TimeModified,EditSequence=$this->EditSequence,TxnNumber=$this->TxnNumber,VendorRef_ListID=$this->VendorRef_ListID,VendorRef_FullName=$this->VendorRef_FullName,VendorAddress_Addr1=$this->VendorAddress_Addr1,VendorAddress_Addr2=$this->VendorAddress_Addr2,VendorAddress_Addr3=$this->VendorAddress_Addr3,VendorAddress_Addr4=$this->VendorAddress_Addr4,VendorAddress_Addr5=$this->VendorAddress_Addr5,VendorAddress_City=$this->VendorAddress_City,VendorAddress_State=$this->VendorAddress_State,VendorAddress_PostalCode=$this->VendorAddress_PostalCode,VendorAddress_Country=$this->VendorAddress_Country,VendorAddress_Note=$this->VendorAddress_Note,APAccountRef_ListID=$this->APAccountRef_ListID,APAccountRef_FullName=$this->APAccountRef_FullName,TxnDate=$this->TxnDate,DueDate=$this->DueDate,AmountDue=$this->AmountDue,CurrencyRef_ListID=$this->CurrencyRef_ListID,CurrencyRef_FullName=$this->CurrencyRef_FullName,ExchangeRate=$this->ExchangeRate,AmountDueInHomeCurrency=$this->AmountDueInHomeCurrency,RefNumber=$this->RefNumber,TermsRef_ListID=$this->TermsRef_ListID,TermsRef_FullName=$this->TermsRef_FullName,Memo=$this->Memo,IsTaxIncluded=$this->IsTaxIncluded,SalesTaxCodeRef_ListID=$this->SalesTaxCodeRef_ListID,SalesTaxCodeRef_FullName=$this->SalesTaxCodeRef_FullName,IsPaID=$this->IsPaID,OpenAmount=$this->OpenAmount,CustomField1=$this->CustomField1,CustomField2=$this->CustomField2,CustomField3=$this->CustomField3,CustomField4=$this->CustomField4,CustomField5=$this->CustomField5,CustomField6=$this->CustomField6,CustomField7=$this->CustomField7,CustomField8=$this->CustomField8,CustomField9=$this->CustomField9,CustomField10=$this->CustomField10,CustomField11=$this->CustomField11,CustomField12=$this->CustomField12,CustomField13=$this->CustomField13,CustomField14=$this->CustomField14,CustomField15=$this->CustomField15,Status=$this->Status WHERE TxnID = :clave;'; 
	$stmt = $this->db->prepare($sql);
	$stmt->bindParam(':clave', $_SESSION['invoice']['TxnID']);
	$stmt->execute();
     } catch(PDOException $e) {
}
     }

}
?>
<!-- end of generated class -->
