
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        lotestrx
* GENERATION DATE:  01.08.2018
* CLASS FILE:       C:\wamp64\www\genera_clase/generated_classes/class.lotestrx.php
* FOR MYSQL TABLE:  lotestrx
* FOR MYSQL DB:     carrillo_dbaurora
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* modify: >> www.aurora-ec.net >> (download for free!)
* -------------------------------------------------------
*
*/
include_once("../resources/class.aurora.php");
// **********************
// CLASS DECLARATION
// **********************

class lotestrx
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************


public $TxnLineID;   // (normal Attribute)
public $TimeCreated;   // (normal Attribute)
public $TimeModified;   // (normal Attribute)
public $EditSequence;   // (normal Attribute)
public $TxnDate;   // (normal Attribute)
public $RefNumber;   // (normal Attribute)
public $ItemRef_ListID;   // (normal Attribute)
public $ItemRef_FullName;   // (normal Attribute)
public $Memo;   // (normal Attribute)
public $MemoTrx;   // (normal Attribute)
public $NumeroTrx;   // (normal Attribute)
public $FechaTrx;   // (normal Attribute)
public $TipoTrx;   // (normal Attribute)
public $OrigenTrx;   // (normal Attribute)
public $DestinoTrx;   // (normal Attribute)
public $QtyTrx;   // (normal Attribute)
public $IDKEY;   // (normal Attribute)
public $Estado;   // (normal Attribute)

var $db; // Instance of class db
var $estado; 


// **********************
// CONSTRUCTOR METHOD
// **********************

function __construct()
{

$this->db = conecta_SYNC();
}

function __destruct()
{


}
public function initialize($entity = null, $options = array())
    {
     $TimeCreated= new Date("TimeCreated");
$TimeCreated->setLabel("TimeCreated");
$TimeCreated->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($TimeCreated);

$TimeModified= new Date("TimeModified");
$TimeModified->setLabel("TimeModified");
$TimeModified->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($TimeModified);

$EditSequence= new Numeric("EditSequence");
$EditSequence->setLabel("EditSequence");
$EditSequence->setFilters(array('int'));
$EditSequence->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($EditSequence);

$TxnDate= new Date("TxnDate");
$TxnDate->setLabel("TxnDate");
$TxnDate->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($TxnDate);

$RefNumber= new Text("RefNumber");
$RefNumber->setLabel("RefNumber");
$RefNumber->setFilters(array('striptags', 'strig'));
$RefNumber->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($RefNumber);

$ItemRef_ListID= new Text("ItemRef_ListID");
$ItemRef_ListID->setLabel("ItemRef_ListID");
$ItemRef_ListID->setFilters(array('striptags', 'strig'));
$ItemRef_ListID->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($ItemRef_ListID);

$ItemRef_FullName= new Text("ItemRef_FullName");
$ItemRef_FullName->setLabel("ItemRef_FullName");
$ItemRef_FullName->setFilters(array('striptags', 'strig'));
$ItemRef_FullName->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($ItemRef_FullName);

$Memo= new Text("Memo");
$Memo->setLabel("Memo");
$Memo->setFilters(array('striptags', 'strig'));
$Memo->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($Memo);

$MemoTrx= new Text("MemoTrx");
$MemoTrx->setLabel("MemoTrx");
$MemoTrx->setFilters(array('striptags', 'strig'));
$MemoTrx->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($MemoTrx);

$NumeroTrx= new Numeric("NumeroTrx");
$NumeroTrx->setLabel("NumeroTrx");
$NumeroTrx->setFilters(array('int'));
$NumeroTrx->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($NumeroTrx);

$FechaTrx= new Date("FechaTrx");
$FechaTrx->setLabel("FechaTrx");
$FechaTrx->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($FechaTrx);

$TipoTrx= new Text("TipoTrx");
$TipoTrx->setLabel("TipoTrx");
$TipoTrx->setFilters(array('striptags', 'strig'));
$TipoTrx->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($TipoTrx);

$OrigenTrx= new Text("OrigenTrx");
$OrigenTrx->setLabel("OrigenTrx");
$OrigenTrx->setFilters(array('striptags', 'strig'));
$OrigenTrx->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($OrigenTrx);

$DestinoTrx= new Text("DestinoTrx");
$DestinoTrx->setLabel("DestinoTrx");
$DestinoTrx->setFilters(array('striptags', 'strig'));
$DestinoTrx->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($DestinoTrx);

$QtyTrx= new Numeric("QtyTrx");
$QtyTrx->setLabel("QtyTrx");
$QtyTrx->setFilters(array('int'));
$QtyTrx->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($QtyTrx);

$IDKEY= new Text("IDKEY");
$IDKEY->setLabel("IDKEY");
$IDKEY->setFilters(array('striptags', 'strig'));
$IDKEY->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($IDKEY);

$Estado= new Text("Estado");
$Estado->setLabel("Estado");
$Estado->setFilters(array('striptags', 'strig'));
$Estado->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($Estado);


    }
    
function genJson_lotestrx($jsonString)
{
$_SESSION['lotestrx']['TxnLineID'] = $jsonString->TxnLineID;
$_SESSION['lotestrx']['TimeCreated'] = $jsonString->TimeCreated;
$_SESSION['lotestrx']['TimeModified'] = $jsonString->TimeModified;
$_SESSION['lotestrx']['EditSequence'] = $jsonString->EditSequence;
$_SESSION['lotestrx']['TxnDate'] = $jsonString->TxnDate;
$_SESSION['lotestrx']['RefNumber'] = $jsonString->RefNumber;
$_SESSION['lotestrx']['ItemRef_ListID'] = $jsonString->ItemRef_ListID;
$_SESSION['lotestrx']['ItemRef_FullName'] = $jsonString->ItemRef_FullName;
$_SESSION['lotestrx']['Memo'] = $jsonString->Memo;
$_SESSION['lotestrx']['MemoTrx'] = $jsonString->MemoTrx;
$_SESSION['lotestrx']['NumeroTrx'] = $jsonString->NumeroTrx;
$_SESSION['lotestrx']['FechaTrx'] = $jsonString->FechaTrx;
$_SESSION['lotestrx']['TipoTrx'] = $jsonString->TipoTrx;
$_SESSION['lotestrx']['OrigenTrx'] = $jsonString->OrigenTrx;
$_SESSION['lotestrx']['DestinoTrx'] = $jsonString->DestinoTrx;
$_SESSION['lotestrx']['QtyTrx'] = $jsonString->QtyTrx;
$_SESSION['lotestrx']['IDKEY'] = $jsonString->IDKEY;
$_SESSION['lotestrx']['Estado'] = $jsonString->Estado;

}

function genInsert_lotestrx()
{
$this->setTxnLineID($_SESSION['lotestrx']['TxnLineID']);
$this->setTimeCreated($_SESSION['lotestrx']['TimeCreated']);
$this->setTimeModified($_SESSION['lotestrx']['TimeModified']);
$this->setEditSequence($_SESSION['lotestrx']['EditSequence']);
$this->setTxnDate($_SESSION['lotestrx']['TxnDate']);
$this->setRefNumber($_SESSION['lotestrx']['RefNumber']);
$this->setItemRef_ListID($_SESSION['lotestrx']['ItemRef_ListID']);
$this->setItemRef_FullName($_SESSION['lotestrx']['ItemRef_FullName']);
$this->setMemo($_SESSION['lotestrx']['Memo']);
$this->setMemoTrx($_SESSION['lotestrx']['MemoTrx']);
$this->setNumeroTrx($_SESSION['lotestrx']['NumeroTrx']);
$this->setFechaTrx($_SESSION['lotestrx']['FechaTrx']);
$this->setTipoTrx($_SESSION['lotestrx']['TipoTrx']);
$this->setOrigenTrx($_SESSION['lotestrx']['OrigenTrx']);
$this->setDestinoTrx($_SESSION['lotestrx']['DestinoTrx']);
$this->setQtyTrx($_SESSION['lotestrx']['QtyTrx']);
$this->setIDKEY($_SESSION['lotestrx']['IDKEY']);
$this->setEstado($_SESSION['lotestrx']['Estado']);

}

function genLimpia_lotestrx()
{
$_SESSION['lotestrx']['TxnLineID'] = ' ';
$_SESSION['lotestrx']['TimeCreated'] = ' ';
$_SESSION['lotestrx']['TimeModified'] = ' ';
$_SESSION['lotestrx']['EditSequence'] = ' ';
$_SESSION['lotestrx']['TxnDate'] = ' ';
$_SESSION['lotestrx']['RefNumber'] = ' ';
$_SESSION['lotestrx']['ItemRef_ListID'] = ' ';
$_SESSION['lotestrx']['ItemRef_FullName'] = ' ';
$_SESSION['lotestrx']['Memo'] = ' ';
$_SESSION['lotestrx']['MemoTrx'] = ' ';
$_SESSION['lotestrx']['NumeroTrx'] = ' ';
$_SESSION['lotestrx']['FechaTrx'] = ' ';
$_SESSION['lotestrx']['TipoTrx'] = ' ';
$_SESSION['lotestrx']['OrigenTrx'] = ' ';
$_SESSION['lotestrx']['DestinoTrx'] = ' ';
$_SESSION['lotestrx']['QtyTrx'] = ' ';
$_SESSION['lotestrx']['IDKEY'] = ' ';
$_SESSION['lotestrx']['Estado'] = ' ';

}

function gentraverse_lotestrx($node)
{
$node->getElementsByTagName('TxnLineID')->item(0) == NULL ? $_SESSION['lotestrx']['TxnLineID'] =  : $_SESSION['lotestrx']['TxnLineID'] = $node->getElementsByTagName('TxnLineID')->item(0)->nodeValue;
$node->getElementsByTagName('TimeCreated')->item(0) == NULL ? $_SESSION['lotestrx']['TimeCreated'] = '2010-08-10' : $_SESSION['lotestrx']['TimeCreated'] = $node->getElementsByTagName('TimeCreated')->item(0)->nodeValue;
$node->getElementsByTagName('TimeModified')->item(0) == NULL ? $_SESSION['lotestrx']['TimeModified'] = '2010-08-10' : $_SESSION['lotestrx']['TimeModified'] = $node->getElementsByTagName('TimeModified')->item(0)->nodeValue;
$node->getElementsByTagName('EditSequence')->item(0) == NULL ? $_SESSION['lotestrx']['EditSequence'] = 0 : $_SESSION['lotestrx']['EditSequence'] = $node->getElementsByTagName('EditSequence')->item(0)->nodeValue;
$node->getElementsByTagName('TxnDate')->item(0) == NULL ? $_SESSION['lotestrx']['TxnDate'] = '2010-08-10' : $_SESSION['lotestrx']['TxnDate'] = $node->getElementsByTagName('TxnDate')->item(0)->nodeValue;
$node->getElementsByTagName('RefNumber')->item(0) == NULL ? $_SESSION['lotestrx']['RefNumber'] = ' ' : $_SESSION['lotestrx']['RefNumber'] = $node->getElementsByTagName('RefNumber')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(0) == NULL ? $_SESSION['lotestrx']['ItemRef_ListID'] = ' ' : $_SESSION['lotestrx']['ItemRef_ListID'] = $node->getElementsByTagName('ListID')->item(0)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['lotestrx']['ItemRef_FullName'] = ' ' : $_SESSION['lotestrx']['ItemRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('Memo')->item(0) == NULL ? $_SESSION['lotestrx']['Memo'] = ' ' : $_SESSION['lotestrx']['Memo'] = $node->getElementsByTagName('Memo')->item(0)->nodeValue;
$node->getElementsByTagName('MemoTrx')->item(0) == NULL ? $_SESSION['lotestrx']['MemoTrx'] = ' ' : $_SESSION['lotestrx']['MemoTrx'] = $node->getElementsByTagName('MemoTrx')->item(0)->nodeValue;
$node->getElementsByTagName('NumeroTrx')->item(0) == NULL ? $_SESSION['lotestrx']['NumeroTrx'] = 0 : $_SESSION['lotestrx']['NumeroTrx'] = $node->getElementsByTagName('NumeroTrx')->item(0)->nodeValue;
$node->getElementsByTagName('FechaTrx')->item(0) == NULL ? $_SESSION['lotestrx']['FechaTrx'] = '2010-08-10' : $_SESSION['lotestrx']['FechaTrx'] = $node->getElementsByTagName('FechaTrx')->item(0)->nodeValue;
$node->getElementsByTagName('TipoTrx')->item(0) == NULL ? $_SESSION['lotestrx']['TipoTrx'] = ' ' : $_SESSION['lotestrx']['TipoTrx'] = $node->getElementsByTagName('TipoTrx')->item(0)->nodeValue;
$node->getElementsByTagName('OrigenTrx')->item(0) == NULL ? $_SESSION['lotestrx']['OrigenTrx'] = ' ' : $_SESSION['lotestrx']['OrigenTrx'] = $node->getElementsByTagName('OrigenTrx')->item(0)->nodeValue;
$node->getElementsByTagName('DestinoTrx')->item(0) == NULL ? $_SESSION['lotestrx']['DestinoTrx'] = ' ' : $_SESSION['lotestrx']['DestinoTrx'] = $node->getElementsByTagName('DestinoTrx')->item(0)->nodeValue;
$node->getElementsByTagName('QtyTrx')->item(0) == NULL ? $_SESSION['lotestrx']['QtyTrx'] = 0 : $_SESSION['lotestrx']['QtyTrx'] = $node->getElementsByTagName('QtyTrx')->item(0)->nodeValue;
$node->getElementsByTagName('IDKEY')->item(0) == NULL ? $_SESSION['lotestrx']['IDKEY'] = ' ' : $_SESSION['lotestrx']['IDKEY'] = $node->getElementsByTagName('IDKEY')->item(0)->nodeValue;
$node->getElementsByTagName('Estado')->item(0) == NULL ? $_SESSION['lotestrx']['Estado'] = ' ' : $_SESSION['lotestrx']['Estado'] = $node->getElementsByTagName('Estado')->item(0)->nodeValue;

}

function adiciona_lotestrx()
{
        $this->estado = 'ERR';
	$this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
        $sql = 'INSERT INTO lotestrx (  TxnLineID, TimeCreated, TimeModified, EditSequence, TxnDate, RefNumber, ItemRef_ListID, ItemRef_FullName, Memo, MemoTrx, NumeroTrx, FechaTrx, TipoTrx, OrigenTrx, DestinoTrx, QtyTrx, IDKEY, Estado) VALUES ( :TxnLineID, :TimeCreated, :TimeModified, :EditSequence, :TxnDate, :RefNumber, :ItemRef_ListID, :ItemRef_FullName, :Memo, :MemoTrx, :NumeroTrx, :FechaTrx, :TipoTrx, :OrigenTrx, :DestinoTrx, :QtyTrx, :IDKEY, :Estado)';
	$stmt = $this->db->prepare($sql);
	 $stmt->bindParam(':TxnLineID', $_SESSION['lotestrx']['TxnLineID'] );
	$stmt->bindParam(':TimeCreated', $_SESSION['lotestrx']['TimeCreated'] );
	$stmt->bindParam(':TimeModified', $_SESSION['lotestrx']['TimeModified'] );
	$stmt->bindParam(':EditSequence', $_SESSION['lotestrx']['EditSequence'] );
	$stmt->bindParam(':TxnDate', $_SESSION['lotestrx']['TxnDate'] );
	$stmt->bindParam(':RefNumber', $_SESSION['lotestrx']['RefNumber'] );
	$stmt->bindParam(':ItemRef_ListID', $_SESSION['lotestrx']['ItemRef_ListID'] );
	$stmt->bindParam(':ItemRef_FullName', $_SESSION['lotestrx']['ItemRef_FullName'] );
	$stmt->bindParam(':Memo', $_SESSION['lotestrx']['Memo'] );
	$stmt->bindParam(':MemoTrx', $_SESSION['lotestrx']['MemoTrx'] );
	$stmt->bindParam(':NumeroTrx', $_SESSION['lotestrx']['NumeroTrx'] );
	$stmt->bindParam(':FechaTrx', $_SESSION['lotestrx']['FechaTrx'] );
	$stmt->bindParam(':TipoTrx', $_SESSION['lotestrx']['TipoTrx'] );
	$stmt->bindParam(':OrigenTrx', $_SESSION['lotestrx']['OrigenTrx'] );
	$stmt->bindParam(':DestinoTrx', $_SESSION['lotestrx']['DestinoTrx'] );
	$stmt->bindParam(':QtyTrx', $_SESSION['lotestrx']['QtyTrx'] );
	$stmt->bindParam(':IDKEY', $_SESSION['lotestrx']['IDKEY'] );
	$stmt->bindParam(':Estado', $_SESSION['lotestrx']['Estado'] );
	$stmt->execute();
        } catch(PDOException $e) {
            echo $e->getMessage();
        }    
}

function quitaslashes_lotestrx()
{
         $_SESSION['lotestrx']['TxnLineID'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['TxnLineID']));
$_SESSION['lotestrx']['TimeCreated'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['TimeCreated']));
$_SESSION['lotestrx']['TimeModified'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['TimeModified']));
$_SESSION['lotestrx']['EditSequence'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['EditSequence']));
$_SESSION['lotestrx']['TxnDate'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['TxnDate']));
$_SESSION['lotestrx']['RefNumber'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['RefNumber']));
$_SESSION['lotestrx']['ItemRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['ItemRef_ListID']));
$_SESSION['lotestrx']['ItemRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['ItemRef_FullName']));
$_SESSION['lotestrx']['Memo'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['Memo']));
$_SESSION['lotestrx']['MemoTrx'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['MemoTrx']));
$_SESSION['lotestrx']['NumeroTrx'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['NumeroTrx']));
$_SESSION['lotestrx']['FechaTrx'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['FechaTrx']));
$_SESSION['lotestrx']['TipoTrx'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['TipoTrx']));
$_SESSION['lotestrx']['OrigenTrx'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['OrigenTrx']));
$_SESSION['lotestrx']['DestinoTrx'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['DestinoTrx']));
$_SESSION['lotestrx']['QtyTrx'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['QtyTrx']));
$_SESSION['lotestrx']['IDKEY'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['IDKEY']));
$_SESSION['lotestrx']['Estado'] = htmlspecialchars(strip_tags($_SESSION['lotestrx']['Estado']));

 
    }
    


// **********************
// GETTER METHODS
// **********************


function getTxnLineID()
{
return $this->TxnLineID;
}

function getTimeCreated()
{
return $this->TimeCreated;
}

function getTimeModified()
{
return $this->TimeModified;
}

function getEditSequence()
{
return $this->EditSequence;
}

function getTxnDate()
{
return $this->TxnDate;
}

function getRefNumber()
{
return $this->RefNumber;
}

function getItemRef_ListID()
{
return $this->ItemRef_ListID;
}

function getItemRef_FullName()
{
return $this->ItemRef_FullName;
}

function getMemo()
{
return $this->Memo;
}

function getMemoTrx()
{
return $this->MemoTrx;
}

function getNumeroTrx()
{
return $this->NumeroTrx;
}

function getFechaTrx()
{
return $this->FechaTrx;
}

function getTipoTrx()
{
return $this->TipoTrx;
}

function getOrigenTrx()
{
return $this->OrigenTrx;
}

function getDestinoTrx()
{
return $this->DestinoTrx;
}

function getQtyTrx()
{
return $this->QtyTrx;
}

function getIDKEY()
{
return $this->IDKEY;
}

function getEstado()
{
return $this->Estado;
}

// **********************
// SETTER METHODS
// **********************


function setTxnLineID($val)
{
$this->TxnLineID =  $val;
}

function setTimeCreated($val)
{
$this->TimeCreated =  $val;
}

function setTimeModified($val)
{
$this->TimeModified =  $val;
}

function setEditSequence($val)
{
$this->EditSequence =  $val;
}

function setTxnDate($val)
{
$this->TxnDate =  $val;
}

function setRefNumber($val)
{
$this->RefNumber =  $val;
}

function setItemRef_ListID($val)
{
$this->ItemRef_ListID =  $val;
}

function setItemRef_FullName($val)
{
$this->ItemRef_FullName =  $val;
}

function setMemo($val)
{
$this->Memo =  $val;
}

function setMemoTrx($val)
{
$this->MemoTrx =  $val;
}

function setNumeroTrx($val)
{
$this->NumeroTrx =  $val;
}

function setFechaTrx($val)
{
$this->FechaTrx =  $val;
}

function setTipoTrx($val)
{
$this->TipoTrx =  $val;
}

function setOrigenTrx($val)
{
$this->OrigenTrx =  $val;
}

function setDestinoTrx($val)
{
$this->DestinoTrx =  $val;
}

function setQtyTrx($val)
{
$this->QtyTrx =  $val;
}

function setIDKEY($val)
{
$this->IDKEY =  $val;
}

function setEstado($val)
{
$this->Estado =  $val;
}

// ************************************************************************************
// SELECT busca igual en el campo estado retorna OK si existe el registro
//          retorna actualiza si es el mismo registro y tambien carga en la instancia
//          los valores de la lectura
// *************************************************************************************

    function buscaIgual_lotestrx() {
        $estado = 'ERR';
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
            $sql =  'SELECT * FROM invoice WHERE TxnID = :clave ';
            $stmt = $this->db->prepare($sql);
            $stmt->bindParam(':clave', $_SESSION['lotestrx']['TxnID']);
            $stmt->execute();
            $registro = $stmt->fetch(PDO::FETCH_ASSOC);
            if ( ! $registro){
                $this->estado = 'OK';
            } else {
                if ($registro['TxnID'] === $_SESSION['lotestrx']['TxnID']) {
                $this->estado = 'ACTUALIZA';
                }
            }
            
        } catch(PDOException $e) {
            echo $e->getMessage();
        } 
    
    return $this->estado;
    }
// ************************************************************************************
// SELECT dependiendo de las condiones recibidas desde el programa llamado se parsea
//          el archivo json para cargar las comparaciones y tambien los nombres de las variables
//          para una lectura de todos los registros que cumplan la condicion
// *************************************************************************************

    function leetodos_lotestrx() {
        $estado = 'ERR';
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
            $sql =  'SELECT * FROM invoice WHERE TxnID = :clave ';
            $stmt = $this->db->prepare($sql);
            $stmt->bindParam(':clave', $_SESSION['lotestrx']['TxnID']);
            $stmt->execute();
            $registro = $stmt->fetchAll(PDO::FETCH_ASSOC);
            if ( ! $registro){
                $this->estado = 'OK';
            } else {
                $this->estado = 'TODOS';
            }
            
        } catch(PDOException $e) {
            echo $e->getMessage();
        } 
    
    return $this->estado;
    }
// **********************
// SELECT METHOD / LOAD
// **********************

function select_lotestrx()
{

$this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	try {
$sql = 'SELECT * FROM lotestrx WHERE TxnLineID = :clave'; 
$stmt = $this->db->prepare($sql);
    $stmt->bindParam(":clave", $_SESSION['lotestrx']['TxnID']);
        $stmt->execute();
	$registro = $stmt->fetch(PDO::FETCH_ASSOC);
	if ( ! $registro) {
		$this->estado = 'OK';
		return $this->estado;
	} else {
                
		if ($registro['TxnID'] === $_SESSION['invoice']['TxnID']) {
                    $this->estado = 'ACTUALIZA';
                    }
                    }
            
                } catch(PDOException $e) {
                    echo $e->getMessage();
                }
                
		$this->TxnLineID = $registro['TxnLineID'];

		$this->TimeCreated = $registro['TimeCreated'];

		$this->TimeModified = $registro['TimeModified'];

		$this->EditSequence = $registro['EditSequence'];

		$this->TxnDate = $registro['TxnDate'];

		$this->RefNumber = $registro['RefNumber'];

		$this->ItemRef_ListID = $registro['ItemRef_ListID'];

		$this->ItemRef_FullName = $registro['ItemRef_FullName'];

		$this->Memo = $registro['Memo'];

		$this->MemoTrx = $registro['MemoTrx'];

		$this->NumeroTrx = $registro['NumeroTrx'];

		$this->FechaTrx = $registro['FechaTrx'];

		$this->TipoTrx = $registro['TipoTrx'];

		$this->OrigenTrx = $registro['OrigenTrx'];

		$this->DestinoTrx = $registro['DestinoTrx'];

		$this->QtyTrx = $registro['QtyTrx'];

		$this->IDKEY = $registro['IDKEY'];

		$this->Estado = $registro['Estado'];


}

// *******************************
// UNSET METHOD / clean
// *******************************

function cleanSession_lotestrx()
{

                unset($_SESSION['lotestrx']['TxnLineID']);
unset($_SESSION['lotestrx']['TimeCreated']);
unset($_SESSION['lotestrx']['TimeModified']);
unset($_SESSION['lotestrx']['EditSequence']);
unset($_SESSION['lotestrx']['TxnDate']);
unset($_SESSION['lotestrx']['RefNumber']);
unset($_SESSION['lotestrx']['ItemRef_ListID']);
unset($_SESSION['lotestrx']['ItemRef_FullName']);
unset($_SESSION['lotestrx']['Memo']);
unset($_SESSION['lotestrx']['MemoTrx']);
unset($_SESSION['lotestrx']['NumeroTrx']);
unset($_SESSION['lotestrx']['FechaTrx']);
unset($_SESSION['lotestrx']['TipoTrx']);
unset($_SESSION['lotestrx']['OrigenTrx']);
unset($_SESSION['lotestrx']['DestinoTrx']);
unset($_SESSION['lotestrx']['QtyTrx']);
unset($_SESSION['lotestrx']['IDKEY']);
unset($_SESSION['lotestrx']['Estado']);


            }

// **********************
// DELETE
// **********************

function delete_lotestrx($id)
{


}

// **********************
// UPDATE
// **********************

function update_lotestrx()
{
    $this->estado = 'ERR';
	 $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            try {
	$sql = 'UPDATE lotestrx SET TimeCreated=$this->TimeCreated, TimeModified=$this->TimeModified, EditSequence=$this->EditSequence, TxnDate=$this->TxnDate, RefNumber=$this->RefNumber, ItemRef_ListID=$this->ItemRef_ListID, ItemRef_FullName=$this->ItemRef_FullName, Memo=$this->Memo, MemoTrx=$this->MemoTrx, NumeroTrx=$this->NumeroTrx, FechaTrx=$this->FechaTrx, TipoTrx=$this->TipoTrx, OrigenTrx=$this->OrigenTrx, DestinoTrx=$this->DestinoTrx, QtyTrx=$this->QtyTrx, IDKEY=$this->IDKEY, Estado=$this->Estado, WHERE TxnLineID = :clave;'; 
	$stmt = $this->db->prepare($sql);
	$stmt->bindParam(':clave', $_SESSION['invoice']['TxnID']);
	$stmt->execute();
     } catch(PDOException $e) {
}
     }

// ---------------------------------------------------------
// Actualiza tabla con la opcion del PDO bindparam
// ---------------------------------------------------------

function actualiza_lotestrx()
{
    $this->estado = 'ERR';
	 $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            try {
	$sql = 'UPDATE lotestrx SET TimeCreated=:TimeCreated, TimeModified=:TimeModified, EditSequence=:EditSequence, TxnDate=:TxnDate, RefNumber=:RefNumber, ItemRef_ListID=:ItemRef_ListID, ItemRef_FullName=:ItemRef_FullName, Memo=:Memo, MemoTrx=:MemoTrx, NumeroTrx=:NumeroTrx, FechaTrx=:FechaTrx, TipoTrx=:TipoTrx, OrigenTrx=:OrigenTrx, DestinoTrx=:DestinoTrx, QtyTrx=:QtyTrx, IDKEY=:IDKEY, Estado=:Estado, WHERE TxnLineID = :clave;'; 
	$stmt = $this->db->prepare($sql);
	 $stmt->bindParam(':TxnLineID', $_SESSION['lotestrx']['TxnLineID'] );
	$stmt->bindParam(':TimeCreated', $_SESSION['lotestrx']['TimeCreated'] );
	$stmt->bindParam(':TimeModified', $_SESSION['lotestrx']['TimeModified'] );
	$stmt->bindParam(':EditSequence', $_SESSION['lotestrx']['EditSequence'] );
	$stmt->bindParam(':TxnDate', $_SESSION['lotestrx']['TxnDate'] );
	$stmt->bindParam(':RefNumber', $_SESSION['lotestrx']['RefNumber'] );
	$stmt->bindParam(':ItemRef_ListID', $_SESSION['lotestrx']['ItemRef_ListID'] );
	$stmt->bindParam(':ItemRef_FullName', $_SESSION['lotestrx']['ItemRef_FullName'] );
	$stmt->bindParam(':Memo', $_SESSION['lotestrx']['Memo'] );
	$stmt->bindParam(':MemoTrx', $_SESSION['lotestrx']['MemoTrx'] );
	$stmt->bindParam(':NumeroTrx', $_SESSION['lotestrx']['NumeroTrx'] );
	$stmt->bindParam(':FechaTrx', $_SESSION['lotestrx']['FechaTrx'] );
	$stmt->bindParam(':TipoTrx', $_SESSION['lotestrx']['TipoTrx'] );
	$stmt->bindParam(':OrigenTrx', $_SESSION['lotestrx']['OrigenTrx'] );
	$stmt->bindParam(':DestinoTrx', $_SESSION['lotestrx']['DestinoTrx'] );
	$stmt->bindParam(':QtyTrx', $_SESSION['lotestrx']['QtyTrx'] );
	$stmt->bindParam(':IDKEY', $_SESSION['lotestrx']['IDKEY'] );
	$stmt->bindParam(':Estado', $_SESSION['lotestrx']['Estado'] );
	$stmt->bindParam(':clave', $_SESSION['invoice']['TxnID']);
	$stmt->execute();
     } catch(PDOException $e) {
}
     }

}
?>
<!-- end of generated class -->
